fronted_app:
    pattern:  /
    defaults: { _controller: AppBundle:Layout:index }

_main:
    resource: routing_rest.yml
    prefix: /api

imag_ldap:
  resource: "@IMAGLdapBundle/Resources/config/routing.yml"
