invest:
    type:     rest
    resource: AppBundle\Controller\InvestController
picklist:
    type:     rest
    resource: AppBundle\Controller\PickListController
location:
    type:     rest
    resource: AppBundle\Controller\LocationController
account:
    type:     rest
    resource: AppBundle\Controller\AccountController
landlord:
    type:     rest
    resource: AppBundle\Controller\LandlordController