invest:
    type:     rest
    resource: AppBundle\Controller\InvestController
photo:
    type:     rest
    parent:   invest
    resource: AppBundle\Controller\PhotoController
picklist:
    type:     rest
    resource: AppBundle\Controller\PickListController
location:
    type:     rest
    resource: AppBundle\Controller\LocationController
account:
    type:     rest
    resource: AppBundle\Controller\AccountController
contact:
    type:     rest
    resource: AppBundle\Controller\ContactController
landlord:
    type:     rest
    resource: AppBundle\Controller\LandlordController
userinfo:
    type:     rest
    resource: AppBundle\Controller\UserinfoController
