<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * KfOppProfserv
 *
 * @ORM\Table(name="KF_OPP_PROFSERV", uniqueConstraints={@ORM\UniqueConstraint(name="KF_OPP_PROFSERV_PRIMARY", columns={"OPPORTUNITYID"})}, indexes={@ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K8", columns={"OPPORTUNITYID", "PROJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K8_K6_K9", columns={"OPPORTUNITYID", "PROJECTID", "SECCODEID", "OBJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K8_1", columns={"PROJECTID", "OPPORTUNITYID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K8_1_6_9", columns={"PROJECTID", "OPPORTUNITYID", "SECCODEID", "OBJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_6_9", columns={"OPPORTUNITYID", "SECCODEID", "OBJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K6_K9_K8", columns={"OPPORTUNITYID", "SECCODEID", "OBJECTID", "PROJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K26_K6_K27_K9_K8_K14_K15_K1_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"AREAID", "SECCODEID", "PROFILEID", "OBJECTID", "PROJECTID", "REGIONID", "CITYID", "OPPORTUNITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K26_K6_K27_K9_K8_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OPPORTUNITYID", "AREAID", "SECCODEID", "PROFILEID", "OBJECTID", "PROJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_6_7_8_9_10_11_12_13_14_15_16_17_19_20_21_22_23_24_25_26_27_28_31", columns={"OPPORTUNITYID", "SECCODEID", "INDUS_INCLUDEOPEX", "PROJECTID", "OBJECTID", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "REGIONID", "CITYID", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "AREAID", "PROFILEID", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K26_K27_K9_K8_K14_K15_K1_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"AREAID", "PROFILEID", "OBJECTID", "PROJECTID", "REGIONID", "CITYID", "OPPORTUNITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_7_8_9_10_11_12_13_14_15_16_17_19_20_21_22_23_24_25_26_27_28_31", columns={"OPPORTUNITYID", "INDUS_INCLUDEOPEX", "PROJECTID", "OBJECTID", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "REGIONID", "CITYID", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "AREAID", "PROFILEID", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K26_K27_K9_K8_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OPPORTUNITYID", "AREAID", "PROFILEID", "OBJECTID", "PROJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_9", columns={"OPPORTUNITYID", "OBJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K8_K9", columns={"OPPORTUNITYID", "PROJECTID", "OBJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K8_1_9", columns={"PROJECTID", "OPPORTUNITYID", "OBJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K9_K8", columns={"OPPORTUNITYID", "OBJECTID", "PROJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K9_K26_K6_K27_K8_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OPPORTUNITYID", "OBJECTID", "AREAID", "SECCODEID", "PROFILEID", "PROJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K9_K1_K26_K6_K27_K8_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OBJECTID", "OPPORTUNITYID", "AREAID", "SECCODEID", "PROFILEID", "PROJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K9_K1", columns={"OBJECTID", "OPPORTUNITYID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K9_K14_K15_K1_11_12_19_20_22_23_25_28", columns={"OBJECTID", "REGIONID", "CITYID", "OPPORTUNITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_9_11_12_14_15_19_20_22_23_25_28", columns={"OPPORTUNITYID", "OBJECTID", "MARKET_SEGMENT", "NOTINDB", "REGIONID", "CITYID", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K9_K1_K14_K15_11_12_19_20_22_23_25_28", columns={"OBJECTID", "OPPORTUNITYID", "REGIONID", "CITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K9_K14_K15_11_12_19_20_22_23_25_28", columns={"OPPORTUNITYID", "OBJECTID", "REGIONID", "CITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K9_K1_K26_K27_K8_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OBJECTID", "OPPORTUNITYID", "AREAID", "PROFILEID", "PROJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K9_K26_K27_K8_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OPPORTUNITYID", "OBJECTID", "AREAID", "PROFILEID", "PROJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K9_K1_K8", columns={"OBJECTID", "OPPORTUNITYID", "PROJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K9", columns={"OBJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K8", columns={"PROJECTID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K6_K9_K14_K15_K1_11_12_19_20_22_23_25_28", columns={"SECCODEID", "OBJECTID", "REGIONID", "CITYID", "OPPORTUNITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K9_K1_K6_K14_K15_11_12_19_20_22_23_25_28", columns={"OBJECTID", "OPPORTUNITYID", "SECCODEID", "REGIONID", "CITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K14_K6_K9_K15_11_12_19_20_22_23_25_28", columns={"OPPORTUNITYID", "REGIONID", "SECCODEID", "OBJECTID", "CITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K15_K1", columns={"CITYID", "OPPORTUNITYID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K15_K1_K6_K9_K14_11_12_19_20_22_23_25_28", columns={"CITYID", "OPPORTUNITYID", "SECCODEID", "OBJECTID", "REGIONID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_6_9_11_12_14_15_19_20_22_23_25_28", columns={"OPPORTUNITYID", "SECCODEID", "OBJECTID", "MARKET_SEGMENT", "NOTINDB", "REGIONID", "CITYID", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K14_K1_K6_K9_K15_11_12_19_20_22_23_25_28", columns={"REGIONID", "OPPORTUNITYID", "SECCODEID", "OBJECTID", "CITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K15_K6_K9_K14_11_12_19_20_22_23_25_28", columns={"OPPORTUNITYID", "CITYID", "SECCODEID", "OBJECTID", "REGIONID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K14_K1", columns={"REGIONID", "OPPORTUNITYID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K6_K9_K14_K15_11_12_19_20_22_23_25_28", columns={"OPPORTUNITYID", "SECCODEID", "OBJECTID", "REGIONID", "CITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K9_K6_K14_K15_11_12_19_20_22_23_25_28", columns={"OPPORTUNITYID", "OBJECTID", "SECCODEID", "REGIONID", "CITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K15", columns={"OPPORTUNITYID", "CITYID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K14", columns={"OPPORTUNITYID", "REGIONID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K15_K26_K27_K9_K8_K14_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OPPORTUNITYID", "CITYID", "AREAID", "PROFILEID", "OBJECTID", "PROJECTID", "REGIONID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K26_K1", columns={"AREAID", "OPPORTUNITYID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K8_K1_K26_K27_K9_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"PROJECTID", "OPPORTUNITYID", "AREAID", "PROFILEID", "OBJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K26_K1_K27_K9_K8_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"AREAID", "OPPORTUNITYID", "PROFILEID", "OBJECTID", "PROJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K27_K26_K9_K8_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OPPORTUNITYID", "PROFILEID", "AREAID", "OBJECTID", "PROJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K27_K1_K26_K9_K8_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"PROFILEID", "OPPORTUNITYID", "AREAID", "OBJECTID", "PROJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K27_K1", columns={"PROFILEID", "OPPORTUNITYID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K27", columns={"OPPORTUNITYID", "PROFILEID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K8_K26_K27_K9_K14_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OPPORTUNITYID", "PROJECTID", "AREAID", "PROFILEID", "OBJECTID", "REGIONID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K15_K1_K26_K27_K9_K8_K14_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"CITYID", "OPPORTUNITYID", "AREAID", "PROFILEID", "OBJECTID", "PROJECTID", "REGIONID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K26", columns={"OPPORTUNITYID", "AREAID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K14_K1_K26_K27_K9_K8_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"REGIONID", "OPPORTUNITYID", "AREAID", "PROFILEID", "OBJECTID", "PROJECTID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K14_K26_K27_K9_K8_K15_7_10_11_12_13_16_17_19_20_21_22_23_24_25_28_31", columns={"OPPORTUNITYID", "REGIONID", "AREAID", "PROFILEID", "OBJECTID", "PROJECTID", "CITYID", "INDUS_INCLUDEOPEX", "CONSULTINGGROUP", "MARKET_SEGMENT", "NOTINDB", "REPORTFORM", "RESEARCHPERIODFROM", "RESEARCHPERIODTO", "VALSERVICES", "TARGET", "SUBTARGET", "ESTCOST", "PROJECT_STAGE", "PROJECT_SUBSTAGE", "OWNERSHIP", "INVSERVICES", "STORAGE_PERCENT"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K1_K6", columns={"OPPORTUNITYID", "SECCODEID"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K6_K1_K9_K14_K15_11_12_19_20_22_23_25_28", columns={"SECCODEID", "OPPORTUNITYID", "OBJECTID", "REGIONID", "CITYID", "MARKET_SEGMENT", "NOTINDB", "VALSERVICES", "TARGET", "ESTCOST", "PROJECT_STAGE", "OWNERSHIP", "INVSERVICES"}), @ORM\Index(name="_dta_index_KF_OPP_PROFSERV_5_1789965453__K6_K1", columns={"SECCODEID", "OPPORTUNITYID"})})
 * @ORM\Entity
 */
class KfOppProfserv
{
    /**
     * @var string
     *
     * @ORM\Column(name="OPPORTUNITYID", type="string", length=12, nullable=false)
     */
    private $opportunityid;

    /**
     * @var string
     *
     * @ORM\Column(name="CREATEUSER", type="string", length=12, nullable=true)
     */
    private $createuser;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="CREATEDATE", type="datetime", nullable=true)
     */
    private $createdate;

    /**
     * @var string
     *
     * @ORM\Column(name="MODIFYUSER", type="string", length=12, nullable=true)
     */
    private $modifyuser;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="MODIFYDATE", type="datetime", nullable=true)
     */
    private $modifydate;

    /**
     * @var string
     *
     * @ORM\Column(name="SECCODEID", type="string", length=12, nullable=true)
     */
    private $seccodeid;

    /**
     * @var string
     *
     * @ORM\Column(name="INDUS_INCLUDEOPEX", type="string", length=1, nullable=true)
     */
    private $indusIncludeopex;

    /**
     * @var string
     *
     * @ORM\Column(name="PROJECTID", type="string", length=12, nullable=true)
     */
    private $projectid;

    /**
     * @var string
     *
     * @ORM\Column(name="OBJECTID", type="string", length=12, nullable=true)
     */
    private $objectid;

    /**
     * @var string
     *
     * @ORM\Column(name="CONSULTINGGROUP", type="string", length=128, nullable=true)
     */
    private $consultinggroup;

    /**
     * @var string
     *
     * @ORM\Column(name="MARKET_SEGMENT", type="string", length=256, nullable=true)
     */
    private $marketSegment;

    /**
     * @var string
     *
     * @ORM\Column(name="NOTINDB", type="string", length=2048, nullable=true)
     */
    private $notindb;

    /**
     * @var string
     *
     * @ORM\Column(name="REPORTFORM", type="string", length=256, nullable=true)
     */
    private $reportform;

    /**
     * @var string
     *
     * @ORM\Column(name="REGIONID", type="string", length=12, nullable=true)
     */
    private $regionid;

    /**
     * @var string
     *
     * @ORM\Column(name="CITYID", type="string", length=12, nullable=true)
     */
    private $cityid;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="RESEARCHPERIODFROM", type="datetime", nullable=true)
     */
    private $researchperiodfrom;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="RESEARCHPERIODTO", type="datetime", nullable=true)
     */
    private $researchperiodto;

    /**
     * @var string
     *
     * @ORM\Column(name="OBJECT_DESCRIPTION", type="text", length=16, nullable=true)
     */
    private $objectDescription;

    /**
     * @var string
     *
     * @ORM\Column(name="VALSERVICES", type="string", length=512, nullable=true)
     */
    private $valservices;

    /**
     * @var string
     *
     * @ORM\Column(name="TARGET", type="string", length=512, nullable=true)
     */
    private $target;

    /**
     * @var string
     *
     * @ORM\Column(name="SUBTARGET", type="string", length=512, nullable=true)
     */
    private $subtarget;

    /**
     * @var string
     *
     * @ORM\Column(name="ESTCOST", type="decimal", precision=17, scale=4, nullable=true)
     */
    private $estcost;

    /**
     * @var string
     *
     * @ORM\Column(name="PROJECT_STAGE", type="string", length=256, nullable=true)
     */
    private $projectStage;

    /**
     * @var string
     *
     * @ORM\Column(name="PROJECT_SUBSTAGE", type="string", length=256, nullable=true)
     */
    private $projectSubstage;

    /**
     * @var string
     *
     * @ORM\Column(name="OWNERSHIP", type="string", length=128, nullable=true)
     */
    private $ownership;

    /**
     * @var string
     *
     * @ORM\Column(name="AREAID", type="string", length=12, nullable=true)
     */
    private $areaid;

    /**
     * @var string
     *
     * @ORM\Column(name="PROFILEID", type="string", length=12, nullable=true)
     */
    private $profileid;

    /**
     * @var string
     *
     * @ORM\Column(name="INVSERVICES", type="string", length=512, nullable=true)
     */
    private $invservices;

    /**
     * @var string
     *
     * @ORM\Column(name="INV_CITY", type="string", length=128, nullable=true)
     */
    private $invCity;

    /**
     * @var string
     *
     * @ORM\Column(name="INV_CITY_TYPE", type="string", length=32, nullable=true)
     */
    private $invCityType;

    /**
     * @var string
     *
     * @ORM\Column(name="STORAGE_PERCENT", type="string", length=1, nullable=true)
     */
    private $storagePercent;


}
