AppBundle\Entity\SpkPhoto:
    exclusion_policy: ALL
    properties:
        spkPhotoId:
            expose: true
#        filename:
#            expose: true
#        Lookups:
#            expose: true
#            groups: [List]
    virtual_properties:
            getUrl:
                serialized_name: url
#            getAvatarUrl:
#                serialized_name: avatar
#            getViewsCount:
#                serialized_name: views
