AppBundle\Entity\Accountdetail:
    type: entity
    table: ACCOUNTDETAIL
    indexes:
        KF_SR_IX_ACCOUNTRUS:
            columns:
                - ACCOUNTID
                - ACCOUNTRUS
        _dta_index_ACCOUNTDETAIL_7_886294217__K1_K6_K23_K25:
            columns:
                - ACCOUNTID
                - ACCOUNTRUS
                - MAINPREFIX
                - FAXPREFIX
        _dta_index_ACCOUNTDETAIL_7_886294217__K6_K23_K25_1:
            columns:
                - ACCOUNTRUS
                - MAINPREFIX
                - FAXPREFIX
                - ACCOUNTID
        _dta_index_ACCOUNTDETAIL_c_7_886294217__K6_K23_K25:
            columns:
                - ACCOUNTRUS
                - MAINPREFIX
                - FAXPREFIX
        _dta_index_ACCOUNTDETAIL_7_886294217__K6_K1:
            columns:
                - ACCOUNTRUS
                - ACCOUNTID
        _dta_index_ACCOUNTDETAIL_7_886294217__K6:
            columns:
                - ACCOUNTRUS
        _dta_index_ACCOUNTDETAIL_7_886294217__K29_K30:
            columns:
                - BRAND
                - FULLNAME
        _dta_index_ACCOUNTDETAIL_7_886294217__K29_K30_K1:
            columns:
                - BRAND
                - FULLNAME
                - ACCOUNTID
        _dta_index_ACCOUNTDETAIL_7_886294217__K1_K29_K30:
            columns:
                - ACCOUNTID
                - BRAND
                - FULLNAME
        _dta_index_ACCOUNTDETAIL_7_886294217__K1_30:
            columns:
                - ACCOUNTID
                - FULLNAME
        _dta_index_ACCOUNTDETAIL_7_886294217__K1_23:
            columns:
                - ACCOUNTID
                - MAINPREFIX
        _dta_index_ACCOUNTDETAIL_7_886294217__K23_K1:
            columns:
                - MAINPREFIX
                - ACCOUNTID
        _dta_index_ACCOUNTDETAIL_7_886294217__K23:
            columns:
                - MAINPREFIX
        _dta_index_ACCOUNTDETAIL_7_886294217__K6_K23_K25_K27_K1:
            columns:
                - ACCOUNTRUS
                - MAINPREFIX
                - FAXPREFIX
                - TOLLPREFIX
                - ACCOUNTID
        _dta_index_ACCOUNTDETAIL_7_886294217__K6_K23_K25_K27:
            columns:
                - ACCOUNTRUS
                - MAINPREFIX
                - FAXPREFIX
                - TOLLPREFIX
        _dta_index_ACCOUNTDETAIL_7_886294217__K1_K6_K23_K25_K27:
            columns:
                - ACCOUNTID
                - ACCOUNTRUS
                - MAINPREFIX
                - FAXPREFIX
                - TOLLPREFIX
        _dta_index_ACCOUNTDETAIL_7_886294217__K1_6_25:
            columns:
                - ACCOUNTID
                - ACCOUNTRUS
                - FAXPREFIX
        _dta_index_ACCOUNTDETAIL_7_886294217__K6_25:
            columns:
                - ACCOUNTRUS
                - FAXPREFIX
        _dta_index_ACCOUNTDETAIL_7_886294217__K6_K1_25:
            columns:
                - ACCOUNTRUS
                - ACCOUNTID
                - FAXPREFIX
        _dta_index_ACCOUNTDETAIL_7_886294217__K6_K1_23_25_27:
            columns:
                - ACCOUNTRUS
                - ACCOUNTID
                - MAINPREFIX
                - FAXPREFIX
                - TOLLPREFIX
        _dta_index_ACCOUNTDETAIL_9_886294217__K6_1_23:
            columns:
                - ACCOUNTRUS
                - ACCOUNTID
                - MAINPREFIX
        _dta_index_ACCOUNTDETAIL_9_886294217__K1_K6_23:
            columns:
                - ACCOUNTID
                - ACCOUNTRUS
                - MAINPREFIX
        _dta_index_ACCOUNTDETAIL_5_886294217__K1_6_29:
            columns:
                - ACCOUNTID
                - ACCOUNTRUS
                - BRAND
        _dta_index_ACCOUNTDETAIL_5_886294217__K6_K23_1:
            columns:
                - ACCOUNTRUS
                - MAINPREFIX
                - ACCOUNTID
        _dta_index_ACCOUNTDETAIL_c_5_886294217__K6_K23:
            columns:
                - ACCOUNTRUS
                - MAINPREFIX
        _dta_index_ACCOUNTDETAIL_5_886294217__K35_K1:
            columns:
                - ACC_NATIONALLITY
                - ACCOUNTID
        _dta_index_ACCOUNTDETAIL_5_886294217__K1_35:
            columns:
                - ACCOUNTID
                - ACC_NATIONALLITY
        _dta_index_ACCOUNTDETAIL_5_886294217__K35:
            columns:
                - ACC_NATIONALLITY
    uniqueConstraints:
        ACCOUNTDETAIL_PRIMARY:
            columns:
                - ACCOUNTID
    id: {  }
    fields:
        accountid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ACCOUNTID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        accountrus:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: ACCOUNTRUS
        acccomment:
            type: string
            nullable: true
            length: 2048
            fixed: false
            column: ACCCOMMENT
        weaknesses:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: WEAKNESSES
        strengths:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: STRENGTHS
        strategy:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: STRATEGY
        rating:
            type: integer
            nullable: true
            unsigned: false
            column: RATING
        products:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: PRODUCTS
        industrialmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: INDUSTRIALMANAGERID
        residentialmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: RESIDENTIALMANAGERID
        countryhousemanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: COUNTRYHOUSEMANAGERID
        retailmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: RETAILMANAGERID
        officesmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: OFFICESMANAGERID
        assessmentmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: ASSESSMENTMANAGERID
        investmentmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: INVESTMENTMANAGERID
        consultingmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: CONSULTINGMANAGERID
        marketreseachmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MARKETRESEACHMANAGERID
        marketingmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MARKETINGMANAGERID
        mainprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MAINPREFIX
        mainsufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MAINSUFIX
        faxprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FAXPREFIX
        faxsufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FAXSUFIX
        tollprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: TOLLPREFIX
        tollsufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: TOLLSUFIX
        brand:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: BRAND
        fullname:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: FULLNAME
        isrussian:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: ISRUSSIAN
        ind:
            type: integer
            nullable: true
            unsigned: false
            column: IND
        numberOfStores:
            type: integer
            nullable: true
            unsigned: false
            column: NUMBER_OF_STORES
        reffered:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: REFFERED
        accNationallity:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: ACC_NATIONALLITY
        otherOffice:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: OTHER_OFFICE
    lifecycleCallbacks: {  }
