AppBundle\Entity\Accountdetail:
    type: entity
    table: ACCOUNTDETAIL
    id:
        accountid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ACCOUNTID
    fields:
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        accountrus:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: ACCOUNTRUS
        acccomment:
            type: string
            nullable: true
            length: 2048
            fixed: false
            column: ACCCOMMENT
        weaknesses:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: WEAKNESSES
        strengths:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: STRENGTHS
        strategy:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: STRATEGY
        rating:
            type: integer
            nullable: true
            unsigned: false
            column: RATING
        products:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: PRODUCTS
        residentialmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: RESIDENTIALMANAGERID
        countryhousemanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: COUNTRYHOUSEMANAGERID
        assessmentmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: ASSESSMENTMANAGERID
        marketreseachmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MARKETRESEACHMANAGERID
        marketingmanagerid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MARKETINGMANAGERID
        mainprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MAINPREFIX
        mainsufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MAINSUFIX
        faxprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FAXPREFIX
        faxsufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FAXSUFIX
        tollprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: TOLLPREFIX
        tollsufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: TOLLSUFIX
        brand:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: BRAND
        fullname:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: FULLNAME
        isrussian:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: ISRUSSIAN
        ind:
            type: integer
            nullable: true
            unsigned: false
            column: IND
        numberOfStores:
            type: integer
            nullable: true
            unsigned: false
            column: NUMBER_OF_STORES
        reffered:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: REFFERED
        accNationallity:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: ACC_NATIONALLITY
        otherOffice:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: OTHER_OFFICE
    lifecycleCallbacks: {  }
    oneToOne:
            account:
                targetEntity: AppBundle\Entity\Account
                inversedBy: detail
                joinColumns:
                    ACCOUNTID:
                        referencedColumnName: ACCOUNTID
                        onDelete: CASCADE
                        onUpdate: CASCADE
    manyToOne:
            officeManager:
                targetEntity: AppBundle\Entity\Userinfo
                joinColumn:
                    name: OFFICESMANAGERID
                    referencedColumnName: USERID
            invetmentManager:
                targetEntity: AppBundle\Entity\Userinfo
                joinColumn:
                    name: INVESTMENTMANAGERID
                    referencedColumnName: USERID
            industrialManager:
                targetEntity: AppBundle\Entity\Userinfo
                joinColumn:
                    name: INDUSTRIALMANAGERID
                    referencedColumnName: USERID
            retailManager:
                targetEntity: AppBundle\Entity\Userinfo
                joinColumn:
                    name: RETAILMANAGERID
                    referencedColumnName: USERID
            consultingManager:
                targetEntity: AppBundle\Entity\Userinfo
                joinColumn:
                    name: CONSULTINGMANAGERID
                    referencedColumnName: USERID
