AppBundle\Entity\ContactStatus:
    type: entity
    table: CONTACT_STATUS
    uniqueConstraints:
        CONTACT_STATUS_PRIMARY:
            columns:
                - CONTACTID
    id: {  }
    fields:
        contactid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: CONTACTID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        seccodeid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SECCODEID
        resiStatus:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: RESI_STATUS
    lifecycleCallbacks: {  }
