AppBundle\Entity\Contactextension:
    type: entity
    table: CONTACTEXTENSION
    uniqueConstraints:
        XPKCONTACTEXTENSION:
            columns:
                - CONTACTID
    id: {  }
    fields:
        contactid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: CONTACTID
        notes:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: NOTES
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
    lifecycleCallbacks: {  }
