AppBundle\Entity\ContactDetail:
    type: entity
    table: CONTACT_DETAIL
    uniqueConstraints:
        CONTACT_DETAIL_PRIMARY:
            columns:
                - CONTACTID
        KF_SR_IX_FIONAME:
            columns:
                - CONTACTID
                - FIRSTRUS
                - MIDDLERUS
                - LASTRUS
                - TITLERUS
                - SUFFIXRUS
                - PREFIXRUS
                - WORKPREFIX
                - WORKSUFIX
                - MOBILEPREFIX
                - MOBILESUFIX
                - HOMEPREFIX
                - HOMESUFIX
                - OTHERPREFIX
                - OTHERSUFIX
                - FAXPREFIX
                - FAXSUFIX
                - NATIONALITY
                - SEX
                - UNSUBSCRIBE
                - NON_DELIVERED
                - TITLE_TYPE
                - KEYCLIENT
    id:
        contactid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: CONTACTID
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: AppBundle\Doctrine\SpkIdGenerator
    fields:
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
            gedmo:
                timestampable:
                    on: create
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
            gedmo:
                timestampable:
                    on: update
        titlerus:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: TITLERUS
        firstrus:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FIRSTRUS
        middlerus:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MIDDLERUS
        lastrus:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: LASTRUS
        suffixrus:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: SUFFIXRUS
        prefixrus:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PREFIXRUS
        workprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: WORKPREFIX
        worksufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: WORKSUFIX
        mobileprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MOBILEPREFIX
        mobilesufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MOBILESUFIX
        homeprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: HOMEPREFIX
        homesufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: HOMESUFIX
        otherprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: OTHERPREFIX
        othersufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: OTHERSUFIX
        faxprefix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FAXPREFIX
        faxsufix:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FAXSUFIX
        nationality:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: NATIONALITY
        sex:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: SEX
        age:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: AGE
        family:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: FAMILY
        numberOfChildren:
            type: smallint
            nullable: true
            unsigned: false
            column: NUMBER_OF_CHILDREN
        leadsourse:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: LEADSOURSE
        workIndustry:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: WORK_INDUSTRY
        hasanimals:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: HASANIMALS
        unsubscribe:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: UNSUBSCRIBE
        nonDelivered:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: NON_DELIVERED
        industrialmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: INDUSTRIALMANAGERID
        residentialmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: RESIDENTIALMANAGERID
        countrymanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: COUNTRYMANAGERID
        retailmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: RETAILMANAGERID
        officemanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: OFFICEMANAGERID
        valuationmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: VALUATIONMANAGERID
        investmentmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: INVESTMENTMANAGERID
        consultingmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CONSULTINGMANAGERID
        researchmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: RESEARCHMANAGERID
        marketingmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MARKETINGMANAGERID
        titleType:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: TITLE_TYPE
        keyclient:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: KEYCLIENT
        sendSms:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: SEND_SMS

    oneToOne:
        contact:
            targetEntity: AppBundle\Entity\Contact
            inversedBy: contactDetail
            joinColumns:
                CONTACTID:
                    referencedColumnName: CONTACTID
                    onDelete: CASCADE
                    onUpdate: CASCADE
    manyToOne:
        createdBy:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: CREATEUSER
                referencedColumnName: USERID
            gedmo:
                blameable:
                    on: create
        updatedBy:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: MODIFYUSER
                referencedColumnName: USERID
            gedmo:
                blameable:
                    on: update

    lifecycleCallbacks: {  }
