AppBundle\Entity\Contact:
    type: entity
    table: CONTACT
    uniqueConstraints:
        KF_SR_CONTACTIDinclACCOUNTID:
            columns:
                - CONTACTID
                - ACCOUNTID
                - LASTNAME
                - FIRSTNAME
                - MIDDLENAME
                - PREFIX
                - SUFFIX
                - ADDRESSID
                - SHIPPINGID
                - WORKPHONE
                - HOMEPHONE
                - FAX
                - MOBILE
                - PAGER
                - PAGERNUMERIC
                - EMAIL
                - SECONDARYEMAIL
                - TITLE
                - BIRTHDAY
                - SECCODEID
                - STATUS
                - LASTNAME_UC
                - DONOTSOLICIT
                - EMAIL3
                - OTHERPHONE
                - LASTHISTORYDATE
                - LASTHISTORYBY
                - SALUTATION
    id:
        contactid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: CONTACTID
    fields:
        type:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: TYPE
        accountid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACCOUNTID
        accountName:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: ACCOUNT
        department:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: DEPARTMENT
        isprimary:
            type: integer
            nullable: true
            unsigned: false
            column: ISPRIMARY
        lastname:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: LASTNAME
        firstname:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FIRSTNAME
        middlename:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MIDDLENAME
        prefix:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: PREFIX
        suffix:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: SUFFIX
        addressid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ADDRESSID
        shippingid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SHIPPINGID
        workphone:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: WORKPHONE
        homephone:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: HOMEPHONE
        fax:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FAX
        mobile:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MOBILE
        pager:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PAGER
        pinnumber:
            type: string
            nullable: true
            length: 7
            fixed: false
            column: PINNUMBER
        pagernumeric:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: PAGERNUMERIC
        email:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: EMAIL
        secondaryemail:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: SECONDARYEMAIL
        webaddress:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: WEBADDRESS
        description:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: DESCRIPTION
        title:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: TITLE
        assistant:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: ASSISTANT
        birthday:
            type: datetime
            nullable: true
            column: BIRTHDAY
        spouse:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: SPOUSE
        spousebirthday:
            type: datetime
            nullable: true
            column: SPOUSEBIRTHDAY
        alumni:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: ALUMNI
        yeargraduated:
            type: integer
            nullable: true
            unsigned: false
            column: YEARGRADUATED
        interests:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: INTERESTS
        previousemployer:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: PREVIOUSEMPLOYER
        directions:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: DIRECTIONS
        reportsto:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: REPORTSTO
        seccodeid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SECCODEID
        accountmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACCOUNTMANAGERID
        regionalmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: REGIONALMANAGERID
        divisionalmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: DIVISIONALMANAGERID
        status:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: STATUS
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
            gedmo:
                timestampable:
                    on: create
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
            gedmo:
                timestampable:
                    on: update
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        referral:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: REFERRAL
        lastnameUc:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: LASTNAME_UC
        initials:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: INITIALS
        alternatekeyprefix:
            type: string
            nullable: true
            length: 8
            fixed: false
            column: ALTERNATEKEYPREFIX
        alternatekeysuffix:
            type: string
            nullable: true
            length: 24
            fixed: false
            column: ALTERNATEKEYSUFFIX
        locationcode:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: LOCATIONCODE
        userfield1:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD1
        userfield2:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD2
        userfield3:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD3
        userfield4:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD4
        userfield5:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD5
        userfield6:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD6
        userfield7:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD7
        userfield8:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD8
        userfield9:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD9
        userfield10:
            type: string
            nullable: true
            length: 80
            fixed: false
            column: USERFIELD10
        webpassword:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: WEBPASSWORD
        webusername:
            type: string
            nullable: true
            length: 30
            fixed: false
            column: WEBUSERNAME
        weight:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: WEIGHT
        donotsolicit:
            type: integer
            nullable: true
            unsigned: false
            column: DONOTSOLICIT
        score:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: SCORE
        email3:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: EMAIL3
        donotemail:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: DONOTEMAIL
        donotphone:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: DONOTPHONE
        donotmail:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: DONOTMAIL
        donotfax:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: DONOTFAX
        importsource:
            type: string
            nullable: true
            length: 24
            fixed: false
            column: IMPORTSOURCE
        subtype:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: SUBTYPE
        otherphone:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: OTHERPHONE
        preferredContact:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: PREFERRED_CONTACT
        webpasswordhint:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: WEBPASSWORDHINT
        isserviceauthorized:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: ISSERVICEAUTHORIZED
        cuisinepref:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: CUISINEPREF
        children:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: CHILDREN
        lasthistorydate:
            type: datetime
            nullable: true
            column: LASTHISTORYDATE
        lasthistoryby:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: LASTHISTORYBY
        webaddress2:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: WEBADDRESS2
        salutation:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: SALUTATION
        subscriberid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SUBSCRIBERID
        categories:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: CATEGORIES
    oneToOne:
        contactDetail:
            targetEntity: AppBundle\Entity\ContactDetail
            mappedBy: contact
            cascade:
                - all
    manyToOne:
        createdBy:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: CREATEUSER
                referencedColumnName: USERID
            gedmo:
                blameable:
                    on: create
        updatedBy:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: MODIFYUSER
                referencedColumnName: USERID
            gedmo:
                blameable:
                    on: update

        account:
          targetEntity: Account
          inversedBy: contacts
          joinColumn:
            name: ACCOUNTID
            referencedColumnName: ACCOUNTID


    lifecycleCallbacks: {  }
