AppBundle\Entity\KfAccountManagerBackup:
    type: entity
    table: kf_account_manager_backup
    id: {  }
    fields:
        accountid:
            type: string
            nullable: false
            length: 12
            fixed: false
        accountmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
    lifecycleCallbacks: {  }
