AppBundle\Entity\KfAccLcs:
    type: entity
    table: kf_acc_lcs
    id: {  }
    fields:
        accountid1:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ACCOUNTID1
        accountid2:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ACCOUNTID2
        account:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: ACCOUNT
        accountrus:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: ACCOUNTrus
        mainphone:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MAINPHONE
        webaddress:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: WEBADDRESS
    lifecycleCallbacks: {  }
