AppBundle\Entity\KfAddressFeatures:
    type: entity
    table: KF_ADDRESS_FEATURES
    uniqueConstraints:
        KF_ADDRESS_FEATURES_PRIMARY:
            columns:
                - ADDRESSID
    id: {  }
    fields:
        addressid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ADDRESSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        addressFeatures:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: ADDRESS_FEATURES
    lifecycleCallbacks: {  }
