AppBundle\Entity\KfAreaSearch:
    type: entity
    table: KF_AREA_SEARCH
    uniqueConstraints:
        KF_AREA_SEARCH_PRIMARY:
            columns:
                - KF_AREA_SEARCHID
    id: {  }
    fields:
        kfAreaSearchid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_AREA_SEARCHID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        searchAreaRus:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: SEARCH_AREA_RUS
        searchAreaEng:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: SEARCH_AREA_ENG
        kfAreaid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: KF_AREAID
    lifecycleCallbacks: {  }
