AppBundle\Entity\KfBestDistrict:
    type: entity
    table: kf_best_district
    id: {  }
    fields:
        bestid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: BESTID
        metroid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: METROID
    lifecycleCallbacks: {  }
