AppBundle\Entity\KfBestStreet:
    type: entity
    table: KF_BEST_STREET
    id: {  }
    fields:
        bestid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: BESTID
        streetid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: STREETID
    lifecycleCallbacks: {  }
