AppBundle\Entity\KfConnector271114:
    type: entity
    table: KF_CONNECTOR_271114
    id: {  }
    fields:
        kfConnectorid:
            type: bigint
            nullable: false
            unsigned: false
            column: KF_CONNECTORID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        isHandle:
            type: smallint
            nullable: false
            unsigned: false
            column: IS_HANDLE
        opCode:
            type: smallint
            nullable: false
            unsigned: false
            column: OP_CODE
    lifecycleCallbacks: {  }
