AppBundle\Entity\KfContactManagers:
    type: entity
    table: KF_CONTACT_MANAGERS
    id: {  }
    fields:
        contactid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CONTACTID
        managerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MANAGERID
    lifecycleCallbacks: {  }
