AppBundle\Entity\KfConnector:
    type: entity
    table: KF_CONNECTOR
    id: {  }
    fields:
        kfConnectorid:
            type: bigint
            nullable: false
            unsigned: false
            column: KF_CONNECTORID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createdate:
            type: datetime
            nullable: true
            default: CURRENT_TIMESTAMP
            column: CREATEDATE
        isHandle:
            type: smallint
            nullable: false
            unsigned: false
            default: '1'
            column: IS_HANDLE
        opCode:
            type: smallint
            nullable: false
            unsigned: false
            column: OP_CODE
    lifecycleCallbacks: {  }
