AppBundle\Entity\KfDelCnt:
    type: entity
    table: kf_del_cnt
    id: {  }
    fields:
        contactid:
            type: string
            nullable: true
            length: 12
            fixed: false
        seccodeid:
            type: string
            nullable: true
            length: 12
            fixed: false
    lifecycleCallbacks: {  }
