AppBundle\Entity\KfGetTrueOpps:
    type: entity
    table: kf_get_true_opps
    id: {  }
    fields:
        accountid:
            type: string
            nullable: false
            length: 12
            fixed: false
    lifecycleCallbacks: {  }
