AppBundle\Entity\KfIndCmpTech:
    type: entity
    table: KF_IND_CMP_TECH
    indexes:
        _dta_index_KF_IND_CMP_TECH_5_397960494__K1_K6_7_8_9_10_11_12_13_14_15_30_31_32_35:
            columns:
                - SPK_PROPERTYID
                - SECCODEID
                - CLASS
                - FACT_AREA
                - FORECAST_AREA
                - LAND_AREA
                - TEMPERATURE
                - MESONIN_AREA
                - OFFICE_AREA
                - TOTAL_AREA
                - MIN_BLOCK_SQUARE
                - DISTANCEFROMCITY
                - COMPLEX_TYPE
                - DIRECTION
                - IS_LISTING
        _dta_index_KF_IND_CMP_TECH_5_397960494__K6_K1_7_8_9_10_11_12_13_14_15_30_31_32_35:
            columns:
                - SECCODEID
                - SPK_PROPERTYID
                - CLASS
                - FACT_AREA
                - FORECAST_AREA
                - LAND_AREA
                - TEMPERATURE
                - MESONIN_AREA
                - OFFICE_AREA
                - TOTAL_AREA
                - MIN_BLOCK_SQUARE
                - DISTANCEFROMCITY
                - COMPLEX_TYPE
                - DIRECTION
                - IS_LISTING
        _dta_index_KF_IND_CMP_TECH_c_5_397960494__K6_K1:
            columns:
                - SECCODEID
                - SPK_PROPERTYID
    uniqueConstraints:
        KF_IND_CMP_TECH_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id: {  }
    fields:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        seccodeid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SECCODEID
        class:
            type: string
            nullable: true
            length: 8
            fixed: false
            column: CLASS
        factArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: FACT_AREA
        forecastArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: FORECAST_AREA
        landArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_AREA
        temperature:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: TEMPERATURE
        mesoninArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: MESONIN_AREA
        officeArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: OFFICE_AREA
        totalArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: TOTAL_AREA
        minBlockSquare:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: MIN_BLOCK_SQUARE
        docks:
            type: integer
            nullable: true
            unsigned: false
            column: DOCKS
        docksType:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: DOCKS_TYPE
        gates:
            type: integer
            nullable: true
            unsigned: false
            column: GATES
        gatesType:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: GATES_TYPE
        parkingIndexCars:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: PARKING_INDEX_CARS
        parkingIndexTrucks:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: PARKING_INDEX_TRUCKS
        parkTypeCars:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: PARK_TYPE_CARS
        parkTypeTrucks:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: PARK_TYPE_TRUCKS
        commentsRus:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: COMMENTS_RUS
        commentsEng:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: COMMENTS_ENG
        commentsParking:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: COMMENTS_PARKING
        electricity:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: ELECTRICITY
        temper:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: TEMPER
        industrialArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: INDUSTRIAL_AREA
        distancefromcity:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: DISTANCEFROMCITY
        complexType:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: COMPLEX_TYPE
        direction:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: DIRECTION
        shareAddress:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: SHARE_ADDRESS
        shareName:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: SHARE_NAME
        isListing:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_LISTING
        ceillingHeightMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CEILLING_HEIGHT_MIN
        ceillingHeightMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CEILLING_HEIGHT_MAX
    lifecycleCallbacks: {  }
