AppBundle\Entity\KfMarketLogs:
    type: entity
    table: KF_MARKET_LOGS
    uniqueConstraints:
        KF_MARKET_LOGS_PRIMARY:
            columns:
                - KF_MARKET_LOGSID
    id: {  }
    fields:
        kfMarketLogsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_MARKET_LOGSID
        kfMarketingProjectsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_MARKETING_PROJECTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        changedField:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: CHANGED_FIELD
        oldValue:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: OLD_VALUE
        newValue:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: NEW_VALUE
        comments:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: COMMENTS
        entity:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: ENTITY
        entityid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ENTITYID
    lifecycleCallbacks: {  }
