AppBundle\Entity\KfMergeRestore:
    type: entity
    table: kf_merge_restore
    id: {  }
    fields:
        newId:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: new_id
        oldId:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: old_id
    lifecycleCallbacks: {  }
