AppBundle\Entity\KfNalPayments:
    type: entity
    table: KF_NAL_PAYMENTS
    id: {  }
    fields:
        kfNalPaymentsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_NAL_PAYMENTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        paymentDate:
            type: datetime
            nullable: true
            column: PAYMENT_DATE
        amount:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: AMOUNT
        managerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MANAGERID
        notes:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: NOTES
        accountid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACCOUNTID
        contactid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CONTACTID
        currency:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: CURRENCY
    lifecycleCallbacks: {  }
