AppBundle\Entity\KfNotification:
    type: entity
    table: kf_notification
    id: {  }
    fields:
        userid:
            type: string
            nullable: false
            length: 12
            fixed: false
        role:
            type: string
            nullable: false
            length: 200
            fixed: false
        typeto:
            type: string
            nullable: false
            length: 50
            fixed: false
        department:
            type: string
            nullable: false
            length: 50
            fixed: false
        createdate:
            type: datetime
            nullable: true
        ssn:
            type: string
            nullable: true
            length: 50
            fixed: false
    lifecycleCallbacks: {  }
