AppBundle\Entity\KfOffBriefParam:
    type: entity
    table: KF_OFF_BRIEF_PARAM
    indexes:
        _dta_index_KF_OFF_BRIEF_PARAM_5_690817523__K1_7:
            columns:
                - SPK_PROPERTYID
                - COMPLEX_NAME
    uniqueConstraints:
        KF_OFF_BRIEF_PARAM_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id: {  }
    fields:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        briefParam:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: BRIEF_PARAM
        complexName:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: COMPLEX_NAME
    lifecycleCallbacks: {  }
