AppBundle\Entity\KfOffArcgis:
    type: entity
    table: KF_OFF_ARCGIS
    uniqueConstraints:
        KF_OFF_ARCGIS_PRIMARY:
            columns:
                - KF_OFF_ARCGISID
    id: {  }
    fields:
        kfOffArcgisid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_OFF_ARCGISID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        compname:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: COMPNAME
        id:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: ID
        nameRus:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: NAME_RUS
        smallAddress:
            type: string
            nullable: true
            length: 1000
            fixed: false
            column: SMALL_ADDRESS
        kfClass:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: KF_CLASS
        status:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: STATUS
        totalArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: TOTAL_AREA
        officeArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: OFFICE_AREA
        leaseArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LEASE_AREA
        complYear:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: COMPL_YEAR
        latitude:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LATITUDE
        longtitude:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LONGTITUDE
        complYearNew:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: COMPL_YEAR_NEW
    lifecycleCallbacks: {  }
