AppBundle\Entity\KfOppDistricts:
    type: entity
    table: KF_OPP_DISTRICTS
    indexes:
        KF_OPP_DISTRICTS_OPPORTUNITYID:
            columns:
                - OPPORTUNITYID
    uniqueConstraints:
        KF_OPP_DISTRICTS_PRIMARY:
            columns:
                - KF_OPP_DISTRICTSID
    id: {  }
    fields:
        kfOppDistrictsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_OPP_DISTRICTSID
        opportunityid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: OPPORTUNITYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        spkDistrictid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SPK_DISTRICTID
    lifecycleCallbacks: {  }
