AppBundle\Entity\KfProjectExport:
    type: entity
    table: KF_PROJECT_EXPORT
    indexes:
        KF_PROJECT_EXPORT_SECCODEID:
            columns:
                - SECCODEID
    uniqueConstraints:
        KF_PROJECT_EXPORT_PRIMARY:
            columns:
                - KF_PROJECTSID
    id: {  }
    fields:
        kfProjectsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_PROJECTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        exportToWeb:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: EXPORT_TO_WEB
        showLocation:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: SHOW_LOCATION
        spkAddressid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SPK_ADDRESSID
        totalArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: TOTAL_AREA
        showClient:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: SHOW_CLIENT
        notes:
            type: string
            nullable: true
            length: 2048
            fixed: false
            column: NOTES
        latitude:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LATITUDE
        longtitude:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LONGTITUDE
        accuracy:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: ACCURACY
        addressText:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: ADDRESS_TEXT
        seccodeid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SECCODEID
    lifecycleCallbacks: {  }
