AppBundle\Entity\KfPropertyActions:
    type: entity
    table: KF_PROPERTY_ACTIONS
    id: {  }
    fields:
        userid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: USERID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        contactid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: CONTACTID
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        type:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: TYPE
    lifecycleCallbacks: {  }
