AppBundle\Entity\KfReqTemp:
    type: entity
    table: kf_REQ_temp
    id: {  }
    fields:
        spkRequestsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQUESTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        managerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MANAGERID
        department:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: DEPARTMENT
        reqType:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: REQ_TYPE
        subtype:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: SUBTYPE
        status:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: STATUS
        contactid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CONTACTID
        notes:
            type: string
            nullable: true
            length: 4000
            fixed: false
            column: NOTES
        seccodeid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SECCODEID
        requirements:
            type: string
            nullable: true
            length: 4000
            fixed: false
            column: REQUIREMENTS
        regiondevelopment:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: REGIONDEVELOPMENT
        terminals:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: TERMINALS
        accountid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACCOUNTID
        spkPropertyid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        areaKf:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: AREA_KF
        areaMoscow:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: AREA_MOSCOW
        avgbill:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: AVGBILL
        bedrooms:
            type: integer
            nullable: true
            unsigned: false
            column: BEDROOMS
        brand:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: BRAND
        budgetMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: BUDGET_MAX
        budgetMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: BUDGET_MIN
        commission:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: COMMISSION
        decorating:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: DECORATING
        distanceToMkad:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: DISTANCE_TO_MKAD
        decorationStyle:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: DECORATION_STYLE
        direction:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: DIRECTION
        entryDate:
            type: datetime
            nullable: true
            column: ENTRY_DATE
        industry:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: INDUSTRY
        isCarPlace:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_CAR_PLACE
        isDecoration:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_DECORATION
        isElectricity:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_ELECTRICITY
        isFurniture:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_FURNITURE
        isHeating:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_HEATING
        isLocalrailway:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_LOCALRAILWAY
        isParking:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_PARKING
        isRailway:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_RAILWAY
        isTimberland:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_TIMBERLAND
        landSquareMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_SQUARE_MAX
        landSquareMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_SQUARE_MIN
        market:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: MARKET
        numberPerson:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: NUMBER_PERSON
        objectType:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: OBJECT_TYPE
        officeSquareMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: OFFICE_SQUARE_MAX
        officeSquareMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: OFFICE_SQUARE_MIN
        parking:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: PARKING
        paymentType:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: PAYMENT_TYPE
        period:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: PERIOD
        preparedness:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: PREPAREDNESS
        profileid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: PROFILEID
        regionNotes:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: REGION_NOTES
        regionid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: REGIONID
        reqDepartment:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: REQ_DEPARTMENT
        reqSubtype:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: REQ_SUBTYPE
        rings:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: RINGS
        roomHeight:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: ROOM_HEIGHT
        roomsCountMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: ROOMS_COUNT_MAX
        roomsCountMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: ROOMS_COUNT_MIN
        security:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: SECURITY
        shopename:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: SHOPENAME
        shosse:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: SHOSSE
        sourceid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SOURCEID
        squareMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: SQUARE_MAX
        squareMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: SQUARE_MIN
        standing:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: STANDING
        subprofileid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SUBPROFILEID
        warehouseType:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: WAREHOUSE_TYPE
        furniture:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FURNITURE
        convertedDate:
            type: datetime
            nullable: true
            column: CONVERTED_DATE
        importSource:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: IMPORT_SOURCE
        duplicate:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: DUPLICATE
        countryStatus:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: COUNTRY_STATUS
        countryHighway:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: COUNTRY_HIGHWAY
        subdivision:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: SUBDIVISION
        notAvailable:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: NOT_AVAILABLE
        isLand:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_LAND
        isWarehouse:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_WAREHOUSE
        industrialHighway:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: INDUSTRIAL_HIGHWAY
        isFirst:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_FIRST
        isRespStorage:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_RESP_STORAGE
    lifecycleCallbacks: {  }
