AppBundle\Entity\KfRotationContacts:
    type: entity
    table: KF_ROTATION_CONTACTS
    uniqueConstraints:
        KF_ROTATION_CONTACTS_PRIMARY:
            columns:
                - CONTACTID
    id: {  }
    fields:
        contactid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: CONTACTID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        oldAccountid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: OLD_ACCOUNTID
        newContactid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: NEW_CONTACTID
        newAccountid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: NEW_ACCOUNTID
        seccodeid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SECCODEID
    lifecycleCallbacks: {  }
