AppBundle\Entity\KfSecurityPersonal:
    type: entity
    table: KF_SECURITY_PERSONAL
    uniqueConstraints:
        KF_SECURITY_PERSONAL_PRIMARY:
            columns:
                - KF_SECURITY_PERSONALID
    id: {  }
    fields:
        kfSecurityPersonalid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_SECURITY_PERSONALID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        userid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: USERID
        location:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: LOCATION
        divisionPalo:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: DIVISION_PALO
        divisionCrm:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: DIVISION_CRM
    lifecycleCallbacks: {  }
