AppBundle\Entity\KfSearchRequests:
    type: entity
    table: KF_SEARCH_REQUESTS
    uniqueConstraints:
        KF_SEARCH_REQUESTS_PRIMARY:
            columns:
                - KF_SEARCH_REQUESTSID
    id: {  }
    fields:
        kfSearchRequestsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_SEARCH_REQUESTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        searchRequests:
            type: string
            nullable: true
            length: 1000
            fixed: false
            column: SEARCH_REQUESTS
    lifecycleCallbacks: {  }
