AppBundle\Entity\KfSitePropertyPics:
    type: entity
    table: kf_site_property_pics
    id: {  }
    fields:
        id:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ID
        slxId:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SLX_ID
        kfId:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: KF_ID
        gpsId:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: GPS_ID
        photoId:
            type: string
            nullable: true
            length: 14
            fixed: false
            column: PHOTO_ID
        modifydate:
            type: datetime
            nullable: true
            default: getutcdate()
            column: MODIFYDATE
        serverLink:
            type: string
            nullable: true
            length: 2000
            fixed: false
            column: SERVER_LINK
        fileSize:
            type: string
            nullable: true
            length: 2000
            fixed: false
            column: file_size
        export:
            type: string
            nullable: true
            length: 10
            fixed: false
            default: '0'
            column: EXPORT
        ptype:
            type: string
            nullable: true
            length: 64
            fixed: false
    lifecycleCallbacks: {  }
