AppBundle\Entity\KfStatusOffice:
    type: entity
    table: KF_STATUS_OFFICE
    uniqueConstraints:
        KF_STATUS_OFFICE_PRIMARY:
            columns:
                - KF_STATUS_OFFICEID
    id: {  }
    fields:
        kfStatusOfficeid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: KF_STATUS_OFFICEID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        status:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: STATUS
        division:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: DIVISION
    lifecycleCallbacks: {  }
