AppBundle\Entity\KfSysUpdateParamTable:
    type: entity
    table: kf_sys_update_param_table
    id: {  }
    fields:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: spk_propertyid
        createdate:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
