AppBundle\Entity\KfTempTableClosedWonOpportunity:
    type: entity
    table: kf_temp_table_closed_won_opportunity
    id: {  }
    fields:
        opportunityid:
            type: string
            nullable: false
            length: 12
            fixed: false
        status:
            type: string
            nullable: true
            length: 64
            fixed: false
    lifecycleCallbacks: {  }
