AppBundle\Entity\KfTempContactEmails3:
    type: entity
    table: kf_temp_contact_emails3
    id: {  }
    fields:
        contactid:
            type: string
            nullable: false
            length: 12
            fixed: false
        email:
            type: string
            nullable: true
            length: 128
            fixed: false
    lifecycleCallbacks: {  }
