AppBundle\Entity\KfUserVisited:
    type: entity
    table: KF_USER_VISITED
    id: {  }
    fields:
        entitytype:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: ENTITYTYPE
        entityid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ENTITYID
        userid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: USERID
        visiteddate:
            type: datetime
            nullable: false
            column: VISITEDDATE
        visiteddatechr:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: VISITEDDATEchr
    lifecycleCallbacks: {  }
