AppBundle\Entity\SpkAccountProfile:
    type: entity
    table: SPK_ACCOUNT_PROFILE
    indexes:
        SPK_ACCOUNT_PROFILE_ACCOUNTID:
            columns:
                - ACCOUNTID
    uniqueConstraints:
        SPK_ACCOUNT_PROFILE_PRIMARY:
            columns:
                - SPK_ACCOUNT_PROFILEID
    id: {  }
    fields:
        spkAccountProfileid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_ACCOUNT_PROFILEID
        accountid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ACCOUNTID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        areaid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: AREAID
        profileid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PROFILEID
        subprofileid:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: SUBPROFILEID
    lifecycleCallbacks: {  }
