AppBundle\Entity\SpkCntLhCommerc:
    type: entity
    table: SPK_CNT_LH_COMMERC
    uniqueConstraints:
        SPK_CNT_LH_COMMERC_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id: {  }
    fields:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        costMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_MIN
        costMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_MAX
        costPerSqmMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_SQM_MIN
        costPerSqmMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_SQM_MAX
        costPer100Min:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_100_MIN
        costPer100Max:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_100_MAX
        costEuroMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_EURO_MIN
        costEuroMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_EURO_MAX
        costPerSqmEuroMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_SQM_EURO_MIN
        costPerSqmEuroMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_SQM_EURO_MAX
        costPer100EuroMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_100_EURO_MIN
        costPer100EuroMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_100_EURO_MAX
        commentsRus:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: COMMENTS_RUS
        commentsEng:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: COMMENTS_ENG
        rentMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: RENT_MIN
        rentMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: RENT_MAX
        costnshared:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: COSTNSHARED
        mainVal:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: MAIN_VAL
        costRurMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_RUR_MIN
        costRurMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_RUR_MAX
        kfFee:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: KF_FEE
        seccodeid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SECCODEID
        rentRur:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: RENT_RUR
        rentEur:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: RENT_EUR
        rentCurrency:
            type: string
            nullable: true
            length: 8
            fixed: false
            column: RENT_CURRENCY
        privateSale:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: PRIVATE_SALE
        costRurSqmMin:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_RUR_SQM_MIN
        costRurSqmMax:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_RUR_SQM_MAX
    lifecycleCallbacks: {  }
