AppBundle\Entity\SpkCntStTech:
    type: entity
    table: SPK_CNT_ST_TECH
    uniqueConstraints:
        SPK_CNT_ST_TECH_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id: {  }
    fields:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        houseTypes:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: HOUSE_TYPES
        houseMaterials:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: HOUSE_MATERIALS
        standartDesignCount:
            type: smallint
            nullable: true
            unsigned: false
            column: STANDART_DESIGN_COUNT
        houseCount:
            type: smallint
            nullable: true
            unsigned: false
            column: HOUSE_COUNT
        storeysCountMin:
            type: smallint
            nullable: true
            unsigned: false
            column: STOREYS_COUNT_MIN
        storeysCountMax:
            type: smallint
            nullable: true
            unsigned: false
            column: STOREYS_COUNT_MAX
        landAreaMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_AREA_MIN
        landAreaMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_AREA_MAX
        totalArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: TOTAL_AREA
        buildingStartQuarter:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: BUILDING_START_QUARTER
        buildingStartYear:
            type: smallint
            nullable: true
            unsigned: false
            column: BUILDING_START_YEAR
        buildingEndQuarter:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: BUILDING_END_QUARTER
        buildingEndYear:
            type: smallint
            nullable: true
            unsigned: false
            column: BUILDING_END_YEAR
        cottageCount:
            type: smallint
            nullable: true
            unsigned: false
            column: COTTAGE_COUNT
        townhouseCount:
            type: smallint
            nullable: true
            unsigned: false
            column: TOWNHOUSE_COUNT
        sewerage:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: SEWERAGE
        electricity:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: ELECTRICITY
        water:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: WATER
        commentsRus:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: COMMENTS_RUS
        commentsEng:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: COMMENTS_ENG
        estimatedHouseCount:
            type: smallint
            nullable: true
            unsigned: false
            column: ESTIMATED_HOUSE_COUNT
        houseAreaMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: HOUSE_AREA_MIN
        houseAreaMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: HOUSE_AREA_MAX
        veryLandArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: VERY_LAND_AREA
        landAreaCottageMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_AREA_COTTAGE_MIN
        landAreaCottageMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_AREA_COTTAGE_MAX
        landAreaTownhouseMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_AREA_TOWNHOUSE_MIN
        landAreaTownhouseMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_AREA_TOWNHOUSE_MAX
        security:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: SECURITY
        kfClass:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: KF_CLASS
        thisProject:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: THIS_PROJECT
        market:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: MARKET
        categoryLandlord:
            type: string
            nullable: true
            length: 24
            fixed: false
            column: CATEGORY_LANDLORD
    lifecycleCallbacks: {  }
