AppBundle\Entity\SpkCntBuildingStage:
    type: entity
    table: SPK_CNT_BUILDING_STAGE
    indexes:
        SPK_CNT_BUILDING_STAGE_SPK_PROPERTYID:
            columns:
                - SPK_PROPERTYID
    uniqueConstraints:
        SPK_CNT_BUILDING_STAGE_PRIMARY:
            columns:
                - SPK_CNT_BUILDING_STAGEID
    id: {  }
    fields:
        spkCntBuildingStageid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_CNT_BUILDING_STAGEID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        stage:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: STAGE
        buldingStartMonth:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: BULDING_START_MONTH
        buildingEndMonth:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: BUILDING_END_MONTH
        stageType:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: STAGE_TYPE
        housesCount:
            type: smallint
            nullable: true
            unsigned: false
            column: HOUSES_COUNT
        availableHousesCount:
            type: smallint
            nullable: true
            unsigned: false
            column: AVAILABLE_HOUSES_COUNT
        houseAreaMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: HOUSE_AREA_MIN
        houseAreaMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: HOUSE_AREA_MAX
        houseType:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: HOUSE_TYPE
        landAreaMin:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_AREA_MIN
        landAreaMax:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: LAND_AREA_MAX
        costMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_MIN
        costMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_MAX
        buildingStartYear:
            type: string
            nullable: true
            length: 4
            fixed: false
            column: BUILDING_START_YEAR
        buildingEndYear:
            type: string
            nullable: true
            length: 4
            fixed: false
            column: BUILDING_END_YEAR
    lifecycleCallbacks: {  }
