AppBundle\Entity\SpkCountry:
    type: entity
    table: SPK_COUNTRY
    indexes:
        SPK_COUNTRY_ID:
            columns:
                - ID
        SPK_COUNTRY_NAME_RUS:
            columns:
                - NAME_RUS
        SPK_COUNTRY_PARENTID:
            columns:
                - PARENTID
        SPK_COUNTRY_SECCODEID:
            columns:
                - SECCODEID
        _dta_index_SPK_COUNTRY_7_612197231__K1_K9_K10_K8_K7_6:
            columns:
                - SPK_PROPERTYID
                - TARGET
                - PROPERTY_TYPE
                - NAME_ENG
                - NAME_RUS
                - ID
        _dta_index_SPK_COUNTRY_7_612197231__K9_K10_K8_K7_K1_6:
            columns:
                - TARGET
                - PROPERTY_TYPE
                - NAME_ENG
                - NAME_RUS
                - SPK_PROPERTYID
                - ID
        _dta_index_SPK_COUNTRY_7_612197231__K9_K10_K8_K7_6:
            columns:
                - TARGET
                - PROPERTY_TYPE
                - NAME_ENG
                - NAME_RUS
                - ID
        _dta_index_SPK_COUNTRY_c_7_612197231__K9_K10_K8_K7:
            columns:
                - TARGET
                - PROPERTY_TYPE
                - NAME_ENG
                - NAME_RUS
        _dta_index_SPK_COUNTRY_7_612197231__K6_1_7_10_17:
            columns:
                - ID
                - SPK_PROPERTYID
                - NAME_RUS
                - PROPERTY_TYPE
                - SECCODEID
        _dta_index_SPK_COUNTRY_7_612197231__K1_K17_K6_7_10:
            columns:
                - SPK_PROPERTYID
                - SECCODEID
                - ID
                - NAME_RUS
                - PROPERTY_TYPE
        _dta_index_SPK_COUNTRY_c_7_612197231__K1_K17:
            columns:
                - SPK_PROPERTYID
                - SECCODEID
        _dta_index_SPK_COUNTRY_7_612197231__K7_K1_6_9_10_11_12_17:
            columns:
                - NAME_RUS
                - SPK_PROPERTYID
                - ID
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
                - SECCODEID
        _dta_index_SPK_COUNTRY_7_612197231__K1_K7_6_9_10_11_12_17:
            columns:
                - SPK_PROPERTYID
                - NAME_RUS
                - ID
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
                - SECCODEID
        _dta_index_SPK_COUNTRY_c_7_612197231__K7_K1:
            columns:
                - NAME_RUS
                - SPK_PROPERTYID
        _dta_index_SPK_COUNTRY_7_612197231__K1_K9_K10_K8_K7_6_17:
            columns:
                - SPK_PROPERTYID
                - TARGET
                - PROPERTY_TYPE
                - NAME_ENG
                - NAME_RUS
                - ID
                - SECCODEID
        _dta_index_SPK_COUNTRY_7_612197231__K1_K6_7_9_10_11_12_17:
            columns:
                - SPK_PROPERTYID
                - ID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
                - SECCODEID
        _dta_index_SPK_COUNTRY_7_612197231__K6_K1_7_9_10_11_12_17:
            columns:
                - ID
                - SPK_PROPERTYID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
                - SECCODEID
        _dta_index_SPK_COUNTRY_c_7_612197231__K6_K1:
            columns:
                - ID
                - SPK_PROPERTYID
        _dta_index_SPK_COUNTRY_7_612197231__K1_K7_6:
            columns:
                - SPK_PROPERTYID
                - NAME_RUS
                - ID
        _dta_index_SPK_COUNTRY_c_7_612197231__K1_K7:
            columns:
                - SPK_PROPERTYID
                - NAME_RUS
        _dta_index_SPK_COUNTRY_5_612197231__K17_K1_7:
            columns:
                - SECCODEID
                - SPK_PROPERTYID
                - NAME_RUS
        _dta_index_SPK_COUNTRY_5_612197231__K10_K9:
            columns:
                - PROPERTY_TYPE
                - TARGET
        _dta_index_SPK_COUNTRY_5_612197231__K9_K10_K1_K7_6:
            columns:
                - TARGET
                - PROPERTY_TYPE
                - SPK_PROPERTYID
                - NAME_RUS
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K1_K10_K9_K7_6:
            columns:
                - SPK_PROPERTYID
                - PROPERTY_TYPE
                - TARGET
                - NAME_RUS
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K10_K9_K1_K7_6:
            columns:
                - PROPERTY_TYPE
                - TARGET
                - SPK_PROPERTYID
                - NAME_RUS
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K10:
            columns:
                - PROPERTY_TYPE
        _dta_index_SPK_COUNTRY_5_612197231__K1_K10_K9:
            columns:
                - SPK_PROPERTYID
                - PROPERTY_TYPE
                - TARGET
        _dta_index_SPK_COUNTRY_5_612197231__K10_K9_K1:
            columns:
                - PROPERTY_TYPE
                - TARGET
                - SPK_PROPERTYID
        _dta_index_SPK_COUNTRY_5_612197231__K1_K7_K10_K9_6:
            columns:
                - SPK_PROPERTYID
                - NAME_RUS
                - PROPERTY_TYPE
                - TARGET
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K9:
            columns:
                - TARGET
        _dta_index_SPK_COUNTRY_5_612197231__K17_K1_K6_7_9_10_11_12:
            columns:
                - SECCODEID
                - SPK_PROPERTYID
                - ID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
        _dta_index_SPK_COUNTRY_5_612197231__K1_K6_K17_7_9_10_11_12:
            columns:
                - SPK_PROPERTYID
                - ID
                - SECCODEID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
        _dta_index_SPK_COUNTRY_5_612197231__K6_K17_K1_7_9_10_11_12:
            columns:
                - ID
                - SECCODEID
                - SPK_PROPERTYID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
        _dta_index_SPK_COUNTRY_5_612197231__K1_K17_6:
            columns:
                - SPK_PROPERTYID
                - SECCODEID
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K17_K1_6:
            columns:
                - SECCODEID
                - SPK_PROPERTYID
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K1_K17_K16_K14_5_6_7_8_9_10_11_12_13_15_18_19:
            columns:
                - SPK_PROPERTYID
                - SECCODEID
                - SPK_STREETID
                - PARENTID
                - MODIFYDATE
                - ID
                - NAME_RUS
                - NAME_ENG
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
                - COMMENTS
                - PROPERTY_NUMBER
                - STREET_NAME_RUS
                - STREET_TYPE_RUS
        _dta_index_SPK_COUNTRY_5_612197231__K17_K16_K1_K14_5_6_7_8_9_10_11_12_13_15_18_19:
            columns:
                - SECCODEID
                - SPK_STREETID
                - SPK_PROPERTYID
                - PARENTID
                - MODIFYDATE
                - ID
                - NAME_RUS
                - NAME_ENG
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
                - COMMENTS
                - PROPERTY_NUMBER
                - STREET_NAME_RUS
                - STREET_TYPE_RUS
        _dta_index_SPK_COUNTRY_5_612197231__K10_K9_K1_K7_6_11_12_17:
            columns:
                - PROPERTY_TYPE
                - TARGET
                - SPK_PROPERTYID
                - NAME_RUS
                - ID
                - STATUS
                - STATUS_KF
                - SECCODEID
        _dta_index_SPK_COUNTRY_5_612197231__K6_K9_1_17:
            columns:
                - ID
                - TARGET
                - SPK_PROPERTYID
                - SECCODEID
        _dta_index_SPK_COUNTRY_5_612197231__K9_K17_K1_K6:
            columns:
                - TARGET
                - SECCODEID
                - SPK_PROPERTYID
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K1_K9_K17_K6:
            columns:
                - SPK_PROPERTYID
                - TARGET
                - SECCODEID
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K6_1_17:
            columns:
                - ID
                - SPK_PROPERTYID
                - SECCODEID
        _dta_index_SPK_COUNTRY_5_612197231__K1_K9:
            columns:
                - SPK_PROPERTYID
                - TARGET
        _dta_index_SPK_COUNTRY_5_612197231__K17_K1_K9_K6:
            columns:
                - SECCODEID
                - SPK_PROPERTYID
                - TARGET
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K9_K1:
            columns:
                - TARGET
                - SPK_PROPERTYID
        _dta_index_SPK_COUNTRY_5_612197231__K9_K1_K17_K6:
            columns:
                - TARGET
                - SPK_PROPERTYID
                - SECCODEID
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K16_K1_K14_5_6_7_8_9_10_11_12_13_15_17_18_19:
            columns:
                - SPK_STREETID
                - SPK_PROPERTYID
                - PARENTID
                - MODIFYDATE
                - ID
                - NAME_RUS
                - NAME_ENG
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
                - COMMENTS
                - PROPERTY_NUMBER
                - SECCODEID
                - STREET_NAME_RUS
                - STREET_TYPE_RUS
        _dta_index_SPK_COUNTRY_5_612197231__K1_6:
            columns:
                - SPK_PROPERTYID
                - ID
        _dta_index_SPK_COUNTRY_5_612197231__K1_K16_K14_5_6_7_8_9_10_11_12_13_15_17_18_19:
            columns:
                - SPK_PROPERTYID
                - SPK_STREETID
                - PARENTID
                - MODIFYDATE
                - ID
                - NAME_RUS
                - NAME_ENG
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
                - COMMENTS
                - PROPERTY_NUMBER
                - SECCODEID
                - STREET_NAME_RUS
                - STREET_TYPE_RUS
        _dta_index_SPK_COUNTRY_5_612197231__K9_K17_K1_K7:
            columns:
                - TARGET
                - SECCODEID
                - SPK_PROPERTYID
                - NAME_RUS
        _dta_index_SPK_COUNTRY_5_612197231__K1_K9_K17_K7:
            columns:
                - SPK_PROPERTYID
                - TARGET
                - SECCODEID
                - NAME_RUS
        _dta_index_SPK_COUNTRY_5_612197231__K17_K1_K9_K7:
            columns:
                - SECCODEID
                - SPK_PROPERTYID
                - TARGET
                - NAME_RUS
        _dta_index_SPK_COUNTRY_5_612197231__K7_1_17:
            columns:
                - NAME_RUS
                - SPK_PROPERTYID
                - SECCODEID
        _dta_index_SPK_COUNTRY_5_612197231__K7_K9_1_17:
            columns:
                - NAME_RUS
                - TARGET
                - SPK_PROPERTYID
                - SECCODEID
        _dta_index_SPK_COUNTRY_5_612197231__K1_K14:
            columns:
                - SPK_PROPERTYID
                - PARENTID
        _dta_index_SPK_COUNTRY_5_612197231__K6_K14_1_7_9_10_11_12_17:
            columns:
                - ID
                - PARENTID
                - SPK_PROPERTYID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
                - SECCODEID
        _dta_index_SPK_COUNTRY_5_612197231__K1_K17_K14_K6_7_9_10_11_12:
            columns:
                - SPK_PROPERTYID
                - SECCODEID
                - PARENTID
                - ID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
        _dta_index_SPK_COUNTRY_5_612197231__K1_K14_K17_K6_7_9_10_11_12:
            columns:
                - SPK_PROPERTYID
                - PARENTID
                - SECCODEID
                - ID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
        _dta_index_SPK_COUNTRY_5_612197231__K1_K17_K6_7_9_10_11_12:
            columns:
                - SPK_PROPERTYID
                - SECCODEID
                - ID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
        _dta_index_SPK_COUNTRY_5_612197231__K14_1:
            columns:
                - PARENTID
                - SPK_PROPERTYID
        _dta_index_SPK_COUNTRY_5_612197231__K14_K1_K17_K6_7_9_10_11_12:
            columns:
                - PARENTID
                - SPK_PROPERTYID
                - SECCODEID
                - ID
                - NAME_RUS
                - TARGET
                - PROPERTY_TYPE
                - STATUS
                - STATUS_KF
        _dta_index_SPK_COUNTRY_5_612197231__K10_K9_K1_K7_6_11_12_14_17:
            columns:
                - PROPERTY_TYPE
                - TARGET
                - SPK_PROPERTYID
                - NAME_RUS
                - ID
                - STATUS
                - STATUS_KF
                - PARENTID
                - SECCODEID
    uniqueConstraints:
        SPK_COUNTRY_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id: {  }
    fields:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        id:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: ID
        nameRus:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: NAME_RUS
        nameEng:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: NAME_ENG
        target:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: TARGET
        propertyType:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PROPERTY_TYPE
        status:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: STATUS
        statusKf:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: STATUS_KF
        comments:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: COMMENTS
        parentid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: PARENTID
        propertyNumber:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: PROPERTY_NUMBER
        spkStreetid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SPK_STREETID
        seccodeid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SECCODEID
        streetNameRus:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: STREET_NAME_RUS
        streetTypeRus:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: STREET_TYPE_RUS
        dogovor:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: DOGOVOR
        startdate:
            type: datetime
            nullable: true
            column: STARTDATE
        enddate:
            type: datetime
            nullable: true
            column: ENDDATE
    lifecycleCallbacks: {  }
