AppBundle\Entity\SpkEmployesTeam:
    type: entity
    table: SPK_EMPLOYES_TEAM
    indexes:
        SPK_EMPLOYES_TEAM_SPK_PROPERTYID:
            columns:
                - SPK_PROPERTYID
    uniqueConstraints:
        SPK_EMPLOYES_TEAM_PRIMARY:
            columns:
                - SPK_EMPLOYES_TEAMID
    id: {  }
    fields:
        spkEmployesTeamid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_EMPLOYES_TEAMID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        team:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: TEAM
        userid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: USERID
        employeRole:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: EMPLOYE_ROLE
        part:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: PART
        comments:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: COMMENTS
    lifecycleCallbacks: {  }
