AppBundle\Entity\SpkInvestEncumbrances:
    type: entity
    table: SPK_INVEST_ENCUMBRANCES
    manyToOne:
        investment:
          targetEntity: SpkInvestment
          inversedBy: encumbrances
          joinColumn:
            name: SPK_PROPERTYID
            referencedColumnName: SPK_PROPERTYID
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            column: ID
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: AppBundle\Doctrine\SpkIdGenerator
    fields:
        encumbranceid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ENCUMBRANCEID
    lifecycleCallbacks: {  }
