AppBundle\Entity\SpkInvestment:
    type: entity
    table: SPK_INVESTMENT
    uniqueConstraints:
        SPK_INVESTMENT_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: AppBundle\Doctrine\SpkIdGenerator
    fields:
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
            gedmo:
                timestampable:
                    on: create
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
            gedmo:
                timestampable:
                    on: update
        seccodeid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SECCODEID
        id:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: ID
        nameRus:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: NAME_RUS
        nameEng:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: NAME_ENG
        propertyType:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PROPERTY_TYPE
        status:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: STATUS
        comments:
            type: string
            nullable: true
            length: 2048
            fixed: false
            column: COMMENTS
        updated:
            type: datetime
            nullable: true
            column: UPDATED
        segment:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: SEGMENT
    lifecycleCallbacks: {  }
    oneToOne:
        property:
            targetEntity: AppBundle\Entity\SpkProperty
            mappedBy: investment
            cascade:
                - all
    oneToMany:
        blocks:
            targetEntity: AppBundle\Entity\SpkInvestBlocks
            mappedBy: investment
            cascade:
                - all
        encumbrances:
            targetEntity: AppBundle\Entity\SpkInvestEncumbrances
            mappedBy: investment
            cascade:
                - all
#        investSegments:
#            targetEntity: AppBundle\Entity\SpkInvestSegments
#            mappedBy: investment
#            cascade:
#                - all
        photos:
            targetEntity: AppBundle\Entity\SpkPhoto
            mappedBy: investment
            cascade:
                - all
    manyToMany:
        landlords:
          targetEntity: AppBundle\Entity\SpkLandlords
          joinTable:
              name: SPK_LANDLORDS
              joinColumns:
                spkPropertyid:
                  referencedColumnName: SPK_PROPERTYID
              inverseJoinColumns:
                spkLandlordsid:
                  referencedColumnName: SPK_LANDLORDSID
          cascade:
              - all
        tenants:
          targetEntity: AppBundle\Entity\SpkTenants
          joinTable:
              name: SPK_TENANTS
              joinColumns:
                spkPropertyid:
                  referencedColumnName: SPK_PROPERTYID
              inverseJoinColumns:
                spkTenantsid:
                  referencedColumnName: SPK_TENANTSID
          cascade:
              - all
    manyToOne:
        createdBy:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: CREATEUSER
                referencedColumnName: USERID
            gedmo:
                blameable:
                    on: create
        updatedBy:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: MODIFYUSER
                referencedColumnName: USERID
            gedmo:
                blameable:
                    on: update
