AppBundle\Entity\SpkInvestEncumbrances:
    type: entity
    table: SPK_INVEST_ENCUMBRANCES
    id: {  }
    fields:
        id:
            type: integer
            nullable: false
            unsigned: false
            column: ID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        encumbranceid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ENCUMBRANCEID
    lifecycleCallbacks: {  }
