AppBundle\Entity\SpkInvestLocation:
    type: entity
    table: SPK_INVEST_LOCATION
    uniqueConstraints:
        SPK_INVEST_LOCATION_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id: {  }
    fields:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        rings:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: RINGS
        mainStreets:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: MAIN_STREETS
    lifecycleCallbacks: {  }
