AppBundle\Entity\SpkIndBuildingStage:
    type: entity
    table: SPK_IND_BUILDING_STAGE
    indexes:
        SPK_IND_BUILDING_STAGE_SPK_PROPERTYID:
            columns:
                - SPK_PROPERTYID
    uniqueConstraints:
        SPK_IND_BUILDING_STAGE_PRIMARY:
            columns:
                - SPK_IND_BUILDING_STAGEID
    id: {  }
    fields:
        spkIndBuildingStageid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_IND_BUILDING_STAGEID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        stage:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: STAGE
        industrialArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: INDUSTRIAL_AREA
        officeArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: OFFICE_AREA
        mesoninArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: MESONIN_AREA
        availiableArea:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: AVAILIABLE_AREA
        startDate:
            type: datetime
            nullable: true
            column: START_DATE
        iscurrent:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: ISCURRENT
        endDate:
            type: datetime
            nullable: true
            column: END_DATE
        finished:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: FINISHED
    lifecycleCallbacks: {  }
