AppBundle\Entity\SpkLandlords:
    type: entity
    table: SPK_LANDLORDS
    uniqueConstraints:
        SPK_LANDLORDS_PRIMARY:
            columns:
                - SPK_LANDLORDSID
    id:
        spkLandlordsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_LANDLORDSID
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: AppBundle\Doctrine\SpkIdGenerator
    fields:
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
            gedmo:
                timestampable:
                    on: create
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
            gedmo:
                timestampable:
                    on: update
        accountid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACCOUNTID
        contactid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CONTACTID
        primaryContact:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: PRIMARY_CONTACT
        contactType:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: CONTACT_TYPE
        partOwned:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PART_OWNED
        startdate:
            type: datetime
            nullable: true
            column: STARTDATE
        enddate:
            type: datetime
            nullable: true
            column: ENDDATE
        currentContact:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: CURRENT_CONTACT
    lifecycleCallbacks: {  }
