AppBundle\Entity\SpkOffDescription:
    type: entity
    table: SPK_OFF_DESCRIPTION
    indexes:
        _dta_index_SPK_OFF_DESCRIPTION_5_1504724413__K1_16:
            columns:
                - SPK_PROPERTYID
                - LONG_BRIEF
    uniqueConstraints:
        SPK_OFF_DESCRIPTION_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id: {  }
    fields:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        briefRus:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: BRIEF_RUS
        briefEng:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: BRIEF_ENG
        siteRus:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: SITE_RUS
        siteEng:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: SITE_ENG
        listingRus:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: LISTING_RUS
        listingEng:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: LISTING_ENG
        siteTarget:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: SITE_TARGET
        ordLease:
            type: integer
            nullable: true
            unsigned: false
            column: ORD_LEASE
        ordSale:
            type: integer
            nullable: true
            unsigned: false
            column: ORD_SALE
        commTermsSite:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: COMM_TERMS_SITE
        longBrief:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: LONG_BRIEF
        specialOffer:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: SPECIAL_OFFER
        specialOfferDescriptionRus:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: SPECIAL_OFFER_DESCRIPTION_RUS
        specialOfferDescriptionEng:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: SPECIAL_OFFER_DESCRIPTION_ENG
        specialOfferSale:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: SPECIAL_OFFER_SALE
        specialOfferDescSaleRus:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: SPECIAL_OFFER_DESC_SALE_RUS
        specialOfferDescSaleEng:
            type: text
            nullable: true
            length: 16
            fixed: false
            column: SPECIAL_OFFER_DESC_SALE_ENG
        infrastructureSite:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: INFRASTRUCTURE_SITE
    lifecycleCallbacks: {  }
