AppBundle\Entity\SpkOppReqObjObject:
    type: entity
    table: SPK_OPP_REQ_OBJ_OBJECT
    indexes:
        SPK_OPP_REQ_OBJ_OBJECT_OPPORTUNITYID:
            columns:
                - OPPORTUNITYID
    uniqueConstraints:
        SPK_OPP_REQ_OBJ_OBJECT_PRIMARY:
            columns:
                - SPK_OPP_REQ_OBJ_OBJECTID
    id: {  }
    fields:
        spkOppReqObjObjectid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_OPP_REQ_OBJ_OBJECTID
        opportunityid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: OPPORTUNITYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        objectid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: OBJECTID
    lifecycleCallbacks: {  }
