AppBundle\Entity\SpkOppList:
    type: entity
    table: SPK_OPP_LIST
    indexes:
        SPK_OPP_LONGLIST_OPPORTUNITYID:
            columns:
                - OPPORTUNITYID
        _dta_index_SPK_OPP_LIST_7_1213247377__K2_K7_1_9_11_12:
            columns:
                - OPPORTUNITYID
                - CONTACTID
                - SPK_OPP_LISTID
                - IN_SHORTLIST
                - SPK_REQUESTSID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_7_1213247377__K7_K2_1_9_11_12:
            columns:
                - CONTACTID
                - OPPORTUNITYID
                - SPK_OPP_LISTID
                - IN_SHORTLIST
                - SPK_REQUESTSID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_c_7_1213247377__K7:
            columns:
                - CONTACTID
        _dta_index_SPK_OPP_LIST_7_1213247377__K2_K9_K7_K3_K11_1_12:
            columns:
                - OPPORTUNITYID
                - IN_SHORTLIST
                - CONTACTID
                - CREATEUSER
                - SPK_REQUESTSID
                - SPK_OPP_LISTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_7_1213247377__K7_K3_K11_K2_K9_1_12:
            columns:
                - CONTACTID
                - CREATEUSER
                - SPK_REQUESTSID
                - OPPORTUNITYID
                - IN_SHORTLIST
                - SPK_OPP_LISTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_c_7_1213247377__K7_K3_K11:
            columns:
                - CONTACTID
                - CREATEUSER
                - SPK_REQUESTSID
        _dta_index_SPK_OPP_LIST_c_7_1213247377__K9_K2:
            columns:
                - IN_SHORTLIST
                - OPPORTUNITYID
        _dta_index_SPK_OPP_LIST_7_1213247377__K12_K7_K9_K2_3:
            columns:
                - SECTION_NAME
                - CONTACTID
                - IN_SHORTLIST
                - OPPORTUNITYID
                - CREATEUSER
        _dta_index_SPK_OPP_LIST_7_1213247377__K2_K9_K7_K3_K12:
            columns:
                - OPPORTUNITYID
                - IN_SHORTLIST
                - CONTACTID
                - CREATEUSER
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_7_1213247377__K7_K3_K2_K9_K12:
            columns:
                - CONTACTID
                - CREATEUSER
                - OPPORTUNITYID
                - IN_SHORTLIST
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_c_7_1213247377__K7_K3:
            columns:
                - CONTACTID
                - CREATEUSER
        _dta_index_SPK_OPP_LIST_c_7_1213247377__K12_K7:
            columns:
                - SECTION_NAME
                - CONTACTID
        _dta_index_SPK_OPP_LIST_7_1213247377__K12_K7_K3_K9_K2:
            columns:
                - SECTION_NAME
                - CONTACTID
                - CREATEUSER
                - IN_SHORTLIST
                - OPPORTUNITYID
        _dta_index_SPK_OPP_LIST_7_1213247377__K7_K2_K3_K9_K12:
            columns:
                - CONTACTID
                - OPPORTUNITYID
                - CREATEUSER
                - IN_SHORTLIST
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_7_1213247377__K2_K3_K9_K7_K12:
            columns:
                - OPPORTUNITYID
                - CREATEUSER
                - IN_SHORTLIST
                - CONTACTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_c_7_1213247377__K3_K9_K2:
            columns:
                - CREATEUSER
                - IN_SHORTLIST
                - OPPORTUNITYID
        _dta_index_SPK_OPP_LIST_5_1213247377__K1_K9_K2_3_7:
            columns:
                - SPK_OPP_LISTID
                - IN_SHORTLIST
                - OPPORTUNITYID
                - CREATEUSER
                - CONTACTID
        _dta_index_SPK_OPP_LIST_5_1213247377__K7_K3_K2_K9_K1:
            columns:
                - CONTACTID
                - CREATEUSER
                - OPPORTUNITYID
                - IN_SHORTLIST
                - SPK_OPP_LISTID
        _dta_index_SPK_OPP_LIST_5_1213247377__K2_K9_K7_K3_K1:
            columns:
                - OPPORTUNITYID
                - IN_SHORTLIST
                - CONTACTID
                - CREATEUSER
                - SPK_OPP_LISTID
        _dta_index_SPK_OPP_LIST_5_1213247377__K2_K9_K7_K3_K1_12:
            columns:
                - OPPORTUNITYID
                - IN_SHORTLIST
                - CONTACTID
                - CREATEUSER
                - SPK_OPP_LISTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_5_1213247377__K7_K3_K2_K9_K1_12:
            columns:
                - CONTACTID
                - CREATEUSER
                - OPPORTUNITYID
                - IN_SHORTLIST
                - SPK_OPP_LISTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_5_1213247377__K1_K9_K2_3_7_12:
            columns:
                - SPK_OPP_LISTID
                - IN_SHORTLIST
                - OPPORTUNITYID
                - CREATEUSER
                - CONTACTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_5_1213247377__K2_K9_K7_K3_K1_11_12:
            columns:
                - OPPORTUNITYID
                - IN_SHORTLIST
                - CONTACTID
                - CREATEUSER
                - SPK_OPP_LISTID
                - SPK_REQUESTSID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_5_1213247377__K2_K7_1_3_9_11_12:
            columns:
                - OPPORTUNITYID
                - CONTACTID
                - SPK_OPP_LISTID
                - CREATEUSER
                - IN_SHORTLIST
                - SPK_REQUESTSID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_5_1213247377__K7_K11_K2_K3_K9_1_12:
            columns:
                - CONTACTID
                - SPK_REQUESTSID
                - OPPORTUNITYID
                - CREATEUSER
                - IN_SHORTLIST
                - SPK_OPP_LISTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_5_1213247377__K2_K3_K9_K7_K11_1_12:
            columns:
                - OPPORTUNITYID
                - CREATEUSER
                - IN_SHORTLIST
                - CONTACTID
                - SPK_REQUESTSID
                - SPK_OPP_LISTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_c_5_1213247377__K7_K11:
            columns:
                - CONTACTID
                - SPK_REQUESTSID
        _dta_index_SPK_OPP_LIST_5_1213247377__K3_K7_K2_K9_1_12:
            columns:
                - CREATEUSER
                - CONTACTID
                - OPPORTUNITYID
                - IN_SHORTLIST
                - SPK_OPP_LISTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_5_1213247377__K2_K9_K3_K7_1_12:
            columns:
                - OPPORTUNITYID
                - IN_SHORTLIST
                - CREATEUSER
                - CONTACTID
                - SPK_OPP_LISTID
                - SECTION_NAME
        _dta_index_SPK_OPP_LIST_c_5_1213247377__K3_K7:
            columns:
                - CREATEUSER
                - CONTACTID
    uniqueConstraints:
        SPK_OPP_LIST_PRIMARY:
            columns:
                - SPK_OPP_LISTID
    id: {  }
    fields:
        spkOppListid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_OPP_LISTID
        opportunityid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: OPPORTUNITYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        contactid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CONTACTID
        result:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: RESULT
        inShortlist:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IN_SHORTLIST
        activityid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACTIVITYID
        spkRequestsid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SPK_REQUESTSID
        sectionName:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: SECTION_NAME
        longlistid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: LONGLISTID
    lifecycleCallbacks: {  }
