AppBundle\Entity\SpkOffBuildingStage:
    type: entity
    table: SPK_OFF_BUILDING_STAGE
    indexes:
        SPK_OFF_BUILDING_STAGE_SPK_PROPERTYID:
            columns:
                - SPK_PROPERTYID
    uniqueConstraints:
        SPK_OFF_BUILDING_STAGE_PRIMARY:
            columns:
                - SPK_OFF_BUILDING_STAGEID
    id: {  }
    fields:
        spkOffBuildingStageid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_OFF_BUILDING_STAGEID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        stage:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: STAGE
        stageDate:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: STAGE_DATE
        preparedness:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: PREPAREDNESS
        comments:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: COMMENTS
        currentStage:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: CURRENT_STAGE
        stageYear:
            type: integer
            nullable: true
            unsigned: false
            column: STAGE_YEAR
        stageQuarter:
            type: smallint
            nullable: true
            unsigned: false
            column: STAGE_QUARTER
        stageMonth:
            type: smallint
            nullable: true
            unsigned: false
            column: STAGE_MONTH
        stageDay:
            type: smallint
            nullable: true
            unsigned: false
            column: STAGE_DAY
        phaseNumber:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: PHASE_NUMBER
    lifecycleCallbacks: {  }
