AppBundle\Entity\SpkOppObjects:
    type: entity
    table: SPK_OPP_OBJECTS
    indexes:
        SPK_OPP_OBJECTS_OPPORTUNITYID:
            columns:
                - OPPORTUNITYID
        _dta_index_SPK_OPP_OBJECTS_5_1024722703__K7_K2_K9_K1:
            columns:
                - OBJECTID
                - OPPORTUNITYID
                - IN_LIST
                - SPK_OPP_OBJECTSID
        _dta_index_SPK_OPP_OBJECTS_5_1024722703__K2_K9_K7_K1:
            columns:
                - OPPORTUNITYID
                - IN_LIST
                - OBJECTID
                - SPK_OPP_OBJECTSID
        _dta_index_SPK_OPP_OBJECTS_5_1024722703__K1_K2_K9_K7:
            columns:
                - SPK_OPP_OBJECTSID
                - OPPORTUNITYID
                - IN_LIST
                - OBJECTID
        _dta_index_SPK_OPP_OBJECTS_5_1024722703__K2_K7_K9_K1:
            columns:
                - OPPORTUNITYID
                - OBJECTID
                - IN_LIST
                - SPK_OPP_OBJECTSID
        _dta_index_SPK_OPP_OBJECTS_c_5_1024722703__K2_K9_K7:
            columns:
                - OPPORTUNITYID
                - IN_LIST
                - OBJECTID
        _dta_index_SPK_OPP_OBJECTS_c_5_1024722703__K7:
            columns:
                - OBJECTID
    uniqueConstraints:
        SPK_OPP_OBJECTS_PRIMARY:
            columns:
                - SPK_OPP_OBJECTSID
    id: {  }
    fields:
        spkOppObjectsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_OPP_OBJECTSID
        opportunityid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: OPPORTUNITYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        objectid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: OBJECTID
        inReport:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IN_REPORT
        inList:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IN_LIST
    lifecycleCallbacks: {  }
