AppBundle\Entity\SpkOppBlocks:
    type: entity
    table: SPK_OPP_BLOCKS
    indexes:
        SPK_OPP_BLOCKS_OPPORTUNITYID:
            columns:
                - OPPORTUNITYID
        _dta_index_SPK_OPP_BLOCKS_7_777769828__K7_K2:
            columns:
                - SPK_PROPERTYID
                - OPPORTUNITYID
        _dta_index_SPK_OPP_BLOCKS_7_777769828__K7:
            columns:
                - SPK_PROPERTYID
        _dta_index_SPK_OPP_BLOCKS_5_777769828__K2_K7_8:
            columns:
                - OPPORTUNITYID
                - SPK_PROPERTYID
                - INCLUDE
        _dta_index_SPK_OPP_BLOCKS_5_777769828__K7_K2_8:
            columns:
                - SPK_PROPERTYID
                - OPPORTUNITYID
                - INCLUDE
    uniqueConstraints:
        SPK_OPP_BLOCKS_PRIMARY:
            columns:
                - SPK_OPP_BLOCKSID
    id: {  }
    fields:
        spkOppBlocksid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_OPP_BLOCKSID
        opportunityid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: OPPORTUNITYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        spkPropertyid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        include:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: INCLUDE
    lifecycleCallbacks: {  }
