AppBundle\Entity\SpkOppPayments:
    type: entity
    table: SPK_OPP_PAYMENTS
    indexes:
        KF_SR_IX_PayDay_incl:
            columns:
                - PAYMENT_DATE
                - AMOUNT
        SPK_OPP_PAYMENTS_OPPORTUNITYID:
            columns:
                - OPPORTUNITYID
        KF_SR_IX_oppID_fls_incl:
            columns:
                - OPPORTUNITYID
                - IS_SUBCONTRACT
                - AMOUNT
    uniqueConstraints:
        SPK_OPP_PAYMENTS_PRIMARY:
            columns:
                - SPK_OPP_PAYMENTSID
    id: {  }
    fields:
        spkOppPaymentsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_OPP_PAYMENTSID
        opportunityid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: OPPORTUNITYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        paymentDate:
            type: datetime
            nullable: true
            column: PAYMENT_DATE
        paymentNumber:
            type: integer
            nullable: true
            unsigned: false
            column: PAYMENT_NUMBER
        amount:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: AMOUNT
        managerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MANAGERID
        notes:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: NOTES
        accountid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACCOUNTID
        contactid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CONTACTID
        vat:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: VAT
        moneyNal:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: MONEY_NAL
        moneyPerevod:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: MONEY_PEREVOD
        moneyOffshore:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: MONEY_OFFSHORE
        isSubcontract:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_SUBCONTRACT
        isPrepayment:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: IS_PREPAYMENT
        currency:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: CURRENCY
        paymentDateCmp:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: PAYMENT_DATE_cmp
    lifecycleCallbacks: {  }
