AppBundle\Entity\SpkProjectTeam:
    type: entity
    table: SPK_PROJECT_TEAM
    indexes:
        SPK_PROJECT_TEAM_SPK_PROPERTYID:
            columns:
                - SPK_PROPERTYID
    uniqueConstraints:
        SPK_PROJECT_TEAM_PRIMARY:
            columns:
                - SPK_PROJECT_TEAMID
    id: {  }
    fields:
        spkProjectTeamid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROJECT_TEAMID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        activityCategory:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: ACTIVITY_CATEGORY
        accountid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACCOUNTID
        comments:
            type: string
            nullable: true
            length: 512
            fixed: false
            column: COMMENTS
    lifecycleCallbacks: {  }
