AppBundle\Entity\SpkPhoto:
    type: entity
    table: SPK_PHOTO
    indexes:
        SPK_PHOTO_SPK_PROPERTYID:
            columns:
                - SPK_PROPERTYID
    uniqueConstraints:
        SPK_PHOTO_PRIMARY:
            columns:
                - SPK_PHOTOID
    id: {  }
    fields:
        spkPhotoid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PHOTOID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        description:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: DESCRIPTION
        photoType:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PHOTO_TYPE
        photoOrder:
            type: smallint
            nullable: true
            unsigned: false
            column: PHOTO_ORDER
        brief:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: BRIEF
        filename:
            type: string
            nullable: true
            length: 256
            fixed: false
            column: FILENAME
        siteOrder:
            type: smallint
            nullable: true
            unsigned: false
            column: SITE_ORDER
        briefOrder:
            type: smallint
            nullable: true
            unsigned: false
            column: BRIEF_ORDER
    lifecycleCallbacks: {  }
