AppBundle\Entity\SpkProperty:
    type: entity
    table: SPK_PROPERTY
    indexes:
        KF_SR_IX_SPK_PropertyID_incl:
            columns:
                - SPK_PROPERTYID
                - SPK_ADDRESSID
    uniqueConstraints:
        SPK_PROPERTY_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id:
        investment:
            associationKey: true
    fields:
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        accountmanagerid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACCOUNTMANAGERID
        export:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: EXPORT
        kfObject:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: KF_OBJECT
        spkAddressid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SPK_ADDRESSID
        importsource:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: IMPORTSOURCE
        competitorObject:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: COMPETITOR_OBJECT
        webaddress:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: WEBADDRESS
        regionObject:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: REGION_OBJECT
        oldid:
            type: integer
            nullable: true
            unsigned: false
        gpsId:
            type: integer
            nullable: true
            unsigned: false
            column: GPS_ID
        investmentPl:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: INVESTMENT
    lifecycleCallbacks: {  }
    oneToOne:
        investment:
            targetEntity: AppBundle\Entity\SpkInvestment
            inversedBy: property
            joinColumns:
                SPK_PROPERTYID:
                    referencedColumnName: SPK_PROPERTYID
                    onDelete: CASCADE
                    onUpdate: CASCADE