AppBundle\Entity\SpkReqObjects:
    type: entity
    table: SPK_REQ_OBJECTS
    indexes:
        SPK_REQ_OBJECTS_SPK_REQ_REQUIREMENTSID:
            columns:
                - SPK_REQ_REQUIREMENTSID
    uniqueConstraints:
        SPK_REQ_OBJECTS_PRIMARY:
            columns:
                - SPK_REQ_OBJECTSID
    id: {  }
    fields:
        spkReqObjectsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQ_OBJECTSID
        spkReqRequirementsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQ_REQUIREMENTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        objectid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: OBJECTID
    lifecycleCallbacks: {  }
