AppBundle\Entity\SpkRetEntertainment:
    type: entity
    table: SPK_RET_ENTERTAINMENT
    indexes:
        SPK_RET_ENTERTAINMENT_SPK_PROPERTYID:
            columns:
                - SPK_PROPERTYID
    uniqueConstraints:
        SPK_RET_ENTERTAINMENT_PRIMARY:
            columns:
                - SPK_RET_ENTERTAINMENTID
    id: {  }
    fields:
        spkRetEntertainmentid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_RET_ENTERTAINMENTID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        entertainmentType:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: ENTERTAINMENT_TYPE
        parameterName:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PARAMETER_NAME
        parameterValue:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: PARAMETER_VALUE
        accountid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ACCOUNTID
        entOrder:
            type: smallint
            nullable: true
            unsigned: false
            column: ENT_ORDER
    lifecycleCallbacks: {  }
