AppBundle\Entity\SpkRequestsPrMgr:
    type: entity
    table: SPK_REQUESTS_PR_MGR
    indexes:
        SPK_REQUESTS_PR_MGR_SPK_REQUESTSID:
            columns:
                - SPK_REQUESTSID
    uniqueConstraints:
        SPK_REQUESTS_PR_MGR_PRIMARY:
            columns:
                - SPK_REQUESTS_PR_MGRID
    id: {  }
    fields:
        spkRequestsPrMgrid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQUESTS_PR_MGRID
        spkRequestsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQUESTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        userid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: USERID
    lifecycleCallbacks: {  }
