AppBundle\Entity\SpkResAptCommerc:
    type: entity
    table: SPK_RES_APT_COMMERC
    indexes:
        _dta_index_SPK_RES_APT_COMMERC_7_552389037__K1_6_7_9:
            columns:
                - SPK_PROPERTYID
                - RENT
                - COST_PER_SQM_MIN
                - COST_MIN
        _dta_index_SPK_RES_APT_COMMERC_7_552389037__K1_6_7_8_9_10_20:
            columns:
                - SPK_PROPERTYID
                - RENT
                - COST_PER_SQM_MIN
                - COST_PER_SQM_MAX
                - COST_MIN
                - COST_MAX
                - CURRENCY_APARTMENT
        _dta_index_SPK_RES_APT_COMMERC_7_552389037__K7_K1_6_9:
            columns:
                - COST_PER_SQM_MIN
                - SPK_PROPERTYID
                - RENT
                - COST_MIN
        _dta_index_SPK_RES_APT_COMMERC_7_552389037__K1_K7_6_9:
            columns:
                - SPK_PROPERTYID
                - COST_PER_SQM_MIN
                - RENT
                - COST_MIN
        _dta_index_SPK_RES_APT_COMMERC_c_7_552389037__K7:
            columns:
                - COST_PER_SQM_MIN
        _dta_index_SPK_RES_APT_COMMERC_5_552389037__K1_9_10:
            columns:
                - SPK_PROPERTYID
                - COST_MIN
                - COST_MAX
        _dta_index_SPK_RES_APT_COMMERC_5_552389037__K1_6_7_9_10:
            columns:
                - SPK_PROPERTYID
                - RENT
                - COST_PER_SQM_MIN
                - COST_MIN
                - COST_MAX
        _dta_index_SPK_RES_APT_COMMERC_5_552389037__K1_6_9_10:
            columns:
                - SPK_PROPERTYID
                - RENT
                - COST_MIN
                - COST_MAX
        _dta_index_SPK_RES_APT_COMMERC_5_552389037__K1_6_7_8_9_10_20_24_25_26_27_28:
            columns:
                - SPK_PROPERTYID
                - RENT
                - COST_PER_SQM_MIN
                - COST_PER_SQM_MAX
                - COST_MIN
                - COST_MAX
                - CURRENCY_APARTMENT
                - COST_EUR_MIN
                - COST_EUR_MAX
                - COST_RUR_MIN
                - COST_RUR_MAX
                - MAIN_VAL
        _dta_index_SPK_RES_APT_COMMERC_5_552389037__K1_6_7_8_9_10_11:
            columns:
                - SPK_PROPERTYID
                - RENT
                - COST_PER_SQM_MIN
                - COST_PER_SQM_MAX
                - COST_MIN
                - COST_MAX
                - CAR_PLACE_COST
        _dta_index_SPK_RES_APT_COMMERC_5_552389037__K1_6_7_8_9_10_11_20_24_25_26_27_28:
            columns:
                - SPK_PROPERTYID
                - RENT
                - COST_PER_SQM_MIN
                - COST_PER_SQM_MAX
                - COST_MIN
                - COST_MAX
                - CAR_PLACE_COST
                - CURRENCY_APARTMENT
                - COST_EUR_MIN
                - COST_EUR_MAX
                - COST_RUR_MIN
                - COST_RUR_MAX
                - MAIN_VAL
        _dta_index_SPK_RES_APT_COMMERC_5_552389037__K6_K7_K8_K1:
            columns:
                - RENT
                - COST_PER_SQM_MIN
                - COST_PER_SQM_MAX
                - SPK_PROPERTYID
        _dta_index_SPK_RES_APT_COMMERC_5_552389037__K1_K6_K7_K8:
            columns:
                - SPK_PROPERTYID
                - RENT
                - COST_PER_SQM_MIN
                - COST_PER_SQM_MAX
        _dta_index_SPK_RES_APT_COMMERC_5_552389037__K1_6_7_8_9_10:
            columns:
                - SPK_PROPERTYID
                - RENT
                - COST_PER_SQM_MIN
                - COST_PER_SQM_MAX
                - COST_MIN
                - COST_MAX
    uniqueConstraints:
        SPK_RES_APT_COMMERC_PRIMARY:
            columns:
                - SPK_PROPERTYID
    id: {  }
    fields:
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        rent:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: RENT
        costPerSqmMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_SQM_MIN
        costPerSqmMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_PER_SQM_MAX
        costMin:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_MIN
        costMax:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COST_MAX
        carPlaceCost:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: CAR_PLACE_COST
        operationalCost:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: OPERATIONAL_COST
        commissionTnPers:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: COMMISSION_TN_PERS
        commissionTn:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COMMISSION_TN
        commissionLrPers:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: COMMISSION_LR_PERS
        commissionLr:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: COMMISSION_LR
        contractType:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: CONTRACT_TYPE
        commentsRus:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: COMMENTS_RUS
        commentsEng:
            type: string
            nullable: true
            length: 1024
            fixed: false
            column: COMMENTS_ENG
        currencyApartment:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: CURRENCY_APARTMENT
        costnotshared:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: COSTNOTSHARED
        costnshared:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: COSTNSHARED
        discount:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: DISCOUNT
        costEurMin:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_EUR_MIN
        costEurMax:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_EUR_MAX
        costRurMin:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_RUR_MIN
        costRurMax:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_RUR_MAX
        mainVal:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: MAIN_VAL
        kfFee:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: KF_FEE
        rentEur:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: RENT_EUR
        rentRur:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: RENT_RUR
        rentCurrency:
            type: string
            nullable: true
            length: 8
            fixed: false
            column: RENT_CURRENCY
        privateSale:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: PRIVATE_SALE
        costEurSqmMin:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_EUR_SQM_MIN
        costEurSqmMax:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_EUR_SQM_MAX
        costRurSqmMin:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_RUR_SQM_MIN
        costRurSqmMax:
            type: decimal
            nullable: true
            precision: 17
            scale: 4
            column: COST_RUR_SQM_MAX
    lifecycleCallbacks: {  }
