AppBundle\Entity\SpkRequestsDistricts:
    type: entity
    table: SPK_REQUESTS_DISTRICTS
    indexes:
        SPK_REQUESTS_DISTRICTS_SPK_REQUESTSID:
            columns:
                - SPK_REQUESTSID
    uniqueConstraints:
        SPK_REQUESTS_DISTRICTS_PRIMARY:
            columns:
                - SPK_REQUESTS_DISTRICTSID
    id: {  }
    fields:
        spkRequestsDistrictsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQUESTS_DISTRICTSID
        spkRequestsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQUESTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        spkDistrictid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SPK_DISTRICTID
    lifecycleCallbacks: {  }
