AppBundle\Entity\SpkRetSpecialists:
    type: entity
    table: SPK_RET_SPECIALISTS
    indexes:
        SPK_RET_SPECIALISTS_SPK_PROPERTYID:
            columns:
                - SPK_PROPERTYID
    uniqueConstraints:
        SPK_RET_SPECIALISTS_PRIMARY:
            columns:
                - SPK_RET_SPECIALISTSID
    id: {  }
    fields:
        spkRetSpecialistsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_RET_SPECIALISTSID
        spkPropertyid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_PROPERTYID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        contactid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CONTACTID
    lifecycleCallbacks: {  }
