AppBundle\Entity\SpkRequestsServices:
    type: entity
    table: SPK_REQUESTS_SERVICES
    indexes:
        SPK_REQUESTS_SERVICES_SPK_REQUESTSID:
            columns:
                - SPK_REQUESTSID
    uniqueConstraints:
        SPK_REQUESTS_SERVICES_PRIMARY:
            columns:
                - SPK_REQUESTS_SERVICESID
    id: {  }
    fields:
        spkRequestsServicesid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQUESTS_SERVICESID
        spkRequestsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQUESTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        serviceid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SERVICEID
    lifecycleCallbacks: {  }
