AppBundle\Entity\SpkRequestsMetro:
    type: entity
    table: SPK_REQUESTS_METRO
    indexes:
        SPK_REQUESTS_METRO_SPK_REQUESTSID:
            columns:
                - SPK_REQUESTSID
    uniqueConstraints:
        SPK_REQUESTS_METRO_PRIMARY:
            columns:
                - SPK_REQUESTS_METROID
    id: {  }
    fields:
        spkRequestsMetroid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQUESTS_METROID
        spkRequestsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_REQUESTSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        spkMetroid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: SPK_METROID
    lifecycleCallbacks: {  }
