AppBundle\Entity\SpkSettings:
    type: entity
    table: SPK_SETTINGS
    uniqueConstraints:
        SPK_SETTINGS_PRIMARY:
            columns:
                - SPK_SETTINGSID
    id: {  }
    fields:
        spkSettingsid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: SPK_SETTINGSID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        spkProperty:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: SPK_PROPERTY
        spkValue:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: SPK_VALUE
    lifecycleCallbacks: {  }
