AppBundle\Entity\Userinfo:
    type: entity
    table: USERINFO
    uniqueConstraints:
        PK_USERINFO:
            columns:
                - USERID
    id:
        userid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: USERID
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: AppBundle\Doctrine\SpkIdGenerator
    fields:
        title:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: TITLE
        username:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: USERNAME
        region:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: REGION
        division:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: DIVISION
        department:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: DEPARTMENT
        email:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: EMAIL
        phone:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PHONE
        direct:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: DIRECT
        home:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: HOME
        fax:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FAX
        mobile:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MOBILE
        pinnumber:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PINNUMBER
        pagerterm:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: PAGERTERM
        addressid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ADDRESSID
        homeaddressid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: HOMEADDRESSID
        altaddressid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ALTADDRESSID
        lastname:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: LASTNAME
        firstname:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: FIRSTNAME
        middlename:
            type: string
            nullable: true
            length: 32
            fixed: false
            column: MIDDLENAME
        prefix:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: PREFIX
        suffix:
            type: string
            nullable: true
            length: 16
            fixed: false
            column: SUFFIX
        accountinguserid:
            type: string
            nullable: true
            length: 512
            fixed: false
            column: ACCOUNTINGUSERID
        available:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: AVAILABLE
        defaultaddknowledge:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: DEFAULTADDKNOWLEDGE
        defectnotify:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: DEFECTNOTIFY
        ticketnotify:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: TICKETNOTIFY
        pagermessagelength:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: PAGERMESSAGELENGTH
        usercompany:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: USERCOMPANY
        timezone:
            type: string
            nullable: true
            length: 64
            fixed: false
            column: TIMEZONE
        windowssid:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: WINDOWSSID
        usewindowsauth:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: USEWINDOWSAUTH
        speedsearchapproval:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: SPEEDSEARCHAPPROVAL
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
            gedmo:
                timestampable:
                    on: create
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
            gedmo:
                timestampable:
                    on: update
        intranetid:
            type: integer
            nullable: true
            unsigned: false
    manyToOne:
        createdBy:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: CREATEUSER
                referencedColumnName: USERID
            gedmo:
                blameable:
                    on: create
        updatedBy:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: MODIFYUSER
                referencedColumnName: USERID
            gedmo:
                blameable:
                    on: update
    lifecycleCallbacks: {  }
