AppBundle\Entity\UserActivityBkp20140408:
    type: entity
    table: user_activity_bkp_20140408
    id: {  }
    fields:
        activityid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: ACTIVITYID
        userid:
            type: string
            nullable: false
            length: 12
            fixed: false
            column: USERID
        confirmed:
            type: integer
            nullable: true
            unsigned: false
            column: CONFIRMED
        alarmtime:
            type: datetime
            nullable: true
            column: ALARMTIME
        alarm:
            type: string
            nullable: true
            length: 1
            fixed: false
            column: ALARM
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
    lifecycleCallbacks: {  }
