AppBundle\Entity\Userrole:
    type: entity
    table: USERROLE
    id: {  }
    fields:
        userroleid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: USERROLEID
        createuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: CREATEUSER
        createdate:
            type: datetime
            nullable: true
            column: CREATEDATE
        modifyuser:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: MODIFYUSER
        modifydate:
            type: datetime
            nullable: true
            column: MODIFYDATE
        userid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: USERID
        roleid:
            type: string
            nullable: true
            length: 12
            fixed: false
            column: ROLEID
    lifecycleCallbacks: {  }
